import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Play, RotateCcw } from 'lucide-react';
import CodeEditor from './CodeEditor';
import ConsolePanel from './ConsolePanel';
import InputPanel from './InputPanel';
import EdgeCasesPanel from './EdgeCasesPanel';

const DEFAULT_JAVA_TEMPLATE = `import java.util.*;

class Solution {
    // Write your solution method here
    public int[] twoSum(int[] nums, int target) {
        // Your code here
        return new int[]{};
    }
}`;

function CodePanel({ problemId, onRunCode, edgeCases, onGenerateEdgeCases, isGeneratingEdgeCases, autoGeneratedInput, functionSignature }) {
  // Initialize code with function signature if available
  const initialCode = functionSignature
    ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
    : DEFAULT_JAVA_TEMPLATE;
    
  const [code, setCode] = useState(initialCode);
  const [stdin, setStdin] = useState('');
  const [activeTab, setActiveTab] = useState('console');
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');
  const [timedOut, setTimedOut] = useState(false);

  // Auto-populate stdin when edge cases are generated
  useEffect(() => {
    if (autoGeneratedInput && autoGeneratedInput.trim()) {
      setStdin(autoGeneratedInput);
    }
  }, [autoGeneratedInput]);

  const handleRunCode = async () => {
    setIsRunning(true);
    setOutput('');
    setError('');
    setTimedOut(false);

    try {
      const result = await onRunCode(code, stdin, problemId);
      
      if (result.timedOut) {
        setTimedOut(true);
        setOutput(result.stdout || '');
        setError(`Execution timed out after ${result.timeout}ms`);
      } else {
        setOutput(result.stdout || result.output || '');
        if (result.stderr) {
          setError(result.stderr);
        }
      }
    } catch (err) {
      setError(err.message || 'Failed to execute code');
    } finally {
      setIsRunning(false);
    }
  };

  const handleReset = () => {
    const resetCode = functionSignature
      ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
      : DEFAULT_JAVA_TEMPLATE;
      
    setCode(resetCode);
    setStdin('');
    setOutput('');
    setError('');
    setTimedOut(false);
  };

  const tabs = [
    { id: 'console', label: 'Output' },
    { id: 'input', label: 'Input' },
    { id: 'edgecases', label: 'Edge Cases', badge: edgeCases?.length || 0 }
  ];

  return (
    <div className="h-full flex flex-col bg-dark-900 rounded-xl border border-dark-800 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-dark-800 bg-dark-900">
        <div className="flex items-center gap-3">
          <span className="text-sm font-semibold text-dark-400">Language:</span>
          <div className="px-3 py-1.5 bg-dark-800 rounded text-sm font-medium text-white border border-dark-700">
            Java
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleReset}
            className="px-3 py-1.5 text-sm text-dark-400 hover:text-white bg-dark-800 hover:bg-dark-700 rounded transition-colors flex items-center gap-1.5"
            title="Reset to default template"
          >
            <RotateCcw className="w-4 h-4" />
            Reset
          </button>
          <button
            onClick={handleRunCode}
            disabled={isRunning}
            className="px-4 py-1.5 bg-brand-orange hover:bg-orange-600 disabled:bg-dark-700 disabled:text-dark-500 text-white rounded font-medium text-sm transition-colors flex items-center gap-2 disabled:cursor-not-allowed"
          >
            {isRunning ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                Running...
              </>
            ) : (
              <>
                <Play className="w-4 h-4 fill-current" />
                Run Code
              </>
            )}
          </button>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 min-h-0 p-4">
        <CodeEditor value={code} onChange={setCode} language="java" />
      </div>

      {/* Bottom Panel with Tabs */}
      <div className="h-64 border-t border-dark-800 flex flex-col">
        {/* Tab Headers */}
        <div className="flex items-center border-b border-dark-800 bg-dark-900">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${
                activeTab === tab.id
                  ? 'border-brand-orange text-white bg-dark-800/50'
                  : 'border-transparent text-dark-400 hover:text-dark-200 hover:bg-dark-800/30'
              }`}
            >
              {tab.label}
              {tab.badge !== undefined && tab.badge > 0 && (
                <span className="ml-2 px-1.5 py-0.5 bg-brand-orange/20 text-brand-orange text-xs rounded-full">
                  {tab.badge}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="flex-1 min-h-0">
          {activeTab === 'console' && (
            <ConsolePanel output={output} error={error} timedOut={timedOut} isRunning={isRunning} />
          )}
          {activeTab === 'input' && (
            <InputPanel stdin={stdin} setStdin={setStdin} />
          )}
          {activeTab === 'edgecases' && (
            <EdgeCasesPanel
              edgeCases={edgeCases}
              isGenerating={isGeneratingEdgeCases}
              onGenerate={onGenerateEdgeCases}
              onCopyInput={(input) => setStdin(input)}
            />
          )}
        </div>
      </div>
    </div>
  );
}

CodePanel.propTypes = {
  problemId: PropTypes.string.isRequired,
  onRunCode: PropTypes.func.isRequired,
  edgeCases: PropTypes.array,
  onGenerateEdgeCases: PropTypes.func,
  isGeneratingEdgeCases: PropTypes.bool,
  autoGeneratedInput: PropTypes.string,
  functionSignature: PropTypes.string
};

export default CodePanel;
