import { useState, useEffect, useRef, useCallback } from 'react';
import PropTypes from 'prop-types';
import { Play, RotateCcw, GripHorizontal } from 'lucide-react';
import CodeEditor from './CodeEditor';
import ConsolePanel from './ConsolePanel';
import InputPanel from './InputPanel';
import EdgeCasesPanel from './EdgeCasesPanel';
import Timer from './Timer';

const DEFAULT_JAVA_TEMPLATE = `import java.util.*;

class Solution {
    // Write your solution method here
    public int[] twoSum(int[] nums, int target) {
        // Your code here
        return new int[]{};
    }
}`;

function CodePanel({ problemId, onRunCode, edgeCases, onGenerateEdgeCases, isGeneratingEdgeCases, autoGeneratedInput, functionSignature }) {
  // Initialize code with function signature if available
  const initialCode = functionSignature
    ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
    : DEFAULT_JAVA_TEMPLATE;
    
  const [code, setCode] = useState(initialCode);
  const [stdin, setStdin] = useState('');
  const [activeTab, setActiveTab] = useState('console');
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');
  const [timedOut, setTimedOut] = useState(false);
  
  // Cooldown State
  const [cooldown, setCooldown] = useState(0);

  useEffect(() => {
    let timer;
    if (cooldown > 0) {
      timer = setInterval(() => {
        setCooldown(prev => prev - 1);
      }, 1000);
    }
    return () => clearInterval(timer);
  }, [cooldown]);
  
  // Resizable panel state
  const [editorHeight, setEditorHeight] = useState(60); // percentage
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef(null);

  // ... (Lines 39-100 preserved) ...

  const handleRunCode = async () => {
    if (cooldown > 0) return;

    setIsRunning(true);
    setOutput('');
    setError('');
    setTimedOut(false);

    try {
      console.log('Running code with stdin:', stdin);
      const result = await onRunCode(code, stdin, problemId);
      console.log('Code execution result:', result);
      
      if (result.timedOut) {
        setTimedOut(true);
        setOutput(result.stdout || '');
        setError(`Execution timed out after ${result.timeout || 3000}ms`);
      } else {
        // Capture all possible output fields
        const outputText = result.stdout || result.output || result.result || '';
        console.log('Setting output to:', outputText);
        setOutput(outputText);
        
        if (result.stderr) {
          console.log('Setting error to:', result.stderr);
          setError(result.stderr);
        }
        
        // If both output and error are empty, show a message
        if (!outputText && !result.stderr && result.exitCode === 0) {
          setOutput('Code executed successfully with no output.');
        }
      }
      // Start cooldown ONLY after successful execution (to prevent punishing errors too hard?)
      // Actually user said "wait 30s between pressing buttons", implying attempts.
      setCooldown(30); 

    } catch (err) {
      console.error('Code execution error:', err);
      setError(err.message || 'Failed to execute code');
    } finally {
      setIsRunning(false);
    }
  };

  const handleReset = () => {
    const resetCode = functionSignature
      ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
      : DEFAULT_JAVA_TEMPLATE;
      
    setCode(resetCode);
    setStdin('');
    setOutput('');
    setError('');
    setTimedOut(false);
  };

  const tabs = [
    { id: 'console', label: 'Output' },
    { id: 'input', label: 'Input' },
    { id: 'edgecases', label: 'Edge Cases', badge: edgeCases?.length || 0 }
  ];

  return (
    <div ref={containerRef} className="h-full flex flex-col bg-dark-950 border-l border-dark-800 overflow-hidden relative">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-dark-800 bg-dark-950/80 backdrop-blur-md shrink-0 z-10">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-dark-500 uppercase tracking-wider">Language</span>
            <div className="px-2 py-1 bg-brand-orange/10 text-brand-orange rounded text-xs font-bold border border-brand-orange/20 flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-brand-orange animate-pulse"></span>
              Java
            </div>
          </div>
          
          <div className="w-px h-4 bg-dark-800 mx-2"></div>
          
          {/* Timer */}
          <Timer autoStart={true} />
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleReset}
            className="p-2 text-dark-400 hover:text-white hover:bg-dark-800 rounded-lg transition-colors group"
            title="Reset to default template"
          >
            <RotateCcw className="w-4 h-4 group-hover:-rotate-90 transition-transform duration-500" />
          </button>
          <button
            onClick={handleRunCode}
            disabled={isRunning || cooldown > 0}
            className="px-4 py-1.5 bg-brand-orange hover:bg-orange-600 disabled:bg-dark-800 disabled:text-dark-500 text-white rounded-lg font-bold text-xs transition-all flex items-center gap-2 disabled:cursor-not-allowed shadow-lg shadow-brand-orange/20 disabled:shadow-none hover:scale-105 active:scale-95"
          >
            {isRunning ? (
              <>
                <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                Running...
              </>
            ) : cooldown > 0 ? (
              <>
                <div className="w-3 h-3 text-dark-500"><Clock className="w-full h-full" /></div>
                Wait {cooldown}s
              </>
            ) : (
              <>
                <Play className="w-3 h-3 fill-current" />
                Run Code
              </>
            )}
          </button>
        </div>
      </div>

      {/* Code Editor - Resizable */}
      <div 
        className="min-h-0 overflow-hidden relative"
        style={{ height: `${editorHeight}%` }}
      >
        <CodeEditor value={code} onChange={setCode} language="java" />
      </div>

      {/* Draggable Divider */}
      <div 
        className="h-3 bg-dark-950 border-y border-dark-800 cursor-row-resize flex items-center justify-center hover:bg-dark-900 transition-colors shrink-0 group z-10"
        onMouseDown={() => setIsDragging(true)}
      >
        <div className="w-12 h-1 rounded-full bg-dark-800 group-hover:bg-brand-orange/50 transition-colors"></div>
      </div>

      {/* Bottom Panel with Tabs - Resizable */}
      <div 
        className="flex flex-col min-h-0 overflow-hidden bg-dark-900/30"
        style={{ height: `${100 - editorHeight}%` }}
      >
        {/* Tab Headers */}
        <div className="flex items-center border-b border-dark-800 bg-dark-950/50 backdrop-blur shrink-0 px-2 pt-2 gap-1">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-t-lg transition-all border-t border-x ${
                activeTab === tab.id
                  ? 'border-dark-800 bg-dark-900 text-white border-b-transparent translate-y-px'
                  : 'border-transparent text-dark-500 hover:text-dark-300 hover:bg-dark-800/50'
              }`}
            >
              {tab.label}
              {tab.badge !== undefined && tab.badge > 0 && (
                <span className="ml-2 px-1.5 py-0.5 bg-brand-orange/20 text-brand-orange text-[10px] rounded-full">
                  {tab.badge}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="flex-1 min-h-0 overflow-hidden bg-dark-900 p-2">
          <div className="h-full rounded-lg border border-dark-800 bg-dark-950/50 overflow-hidden">
            {activeTab === 'console' && (
              <ConsolePanel 
                output={output} 
                error={error} 
                timedOut={timedOut} 
                isLoading={isRunning} 
                testCases={edgeCases}
              />
            )}
            {activeTab === 'input' && (
              <InputPanel value={stdin} onChange={setStdin} />
            )}
            {activeTab === 'edgecases' && (
              <EdgeCasesPanel
                edgeCases={edgeCases}
                isGenerating={isGeneratingEdgeCases}
                onGenerate={onGenerateEdgeCases}
                onCopyInput={(input) => setStdin(input)}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

CodePanel.propTypes = {
  problemId: PropTypes.string.isRequired,
  onRunCode: PropTypes.func.isRequired,
  edgeCases: PropTypes.array,
  onGenerateEdgeCases: PropTypes.func,
  isGeneratingEdgeCases: PropTypes.bool,
  autoGeneratedInput: PropTypes.string,
  functionSignature: PropTypes.string
};

export default CodePanel;

