import { useState, useEffect, useRef, useCallback } from 'react';
import PropTypes from 'prop-types';
import { Play, RotateCcw, GripHorizontal, Clock, Cpu, Brain, CheckCircle, AlertTriangle, Lightbulb, TrendingUp, X, Star } from 'lucide-react';
import CodeEditor from './CodeEditor';
import ConsolePanel from './ConsolePanel';
import InputPanel from './InputPanel';
import EdgeCasesPanel from './EdgeCasesPanel';
import Timer from './Timer';

const DEFAULT_JAVA_TEMPLATE = `import java.util.*;

class Solution {
    // Write your solution method here
    public int[] twoSum(int[] nums, int target) {
        // Your code here
        return new int[]{};
    }
}`;

function CodePanel({ 
  problemId, 
  onRunCode, 
  edgeCases, 
  onGenerateEdgeCases, 
  isGeneratingEdgeCases, 
  autoGeneratedInput, 
  functionSignature,
  // New props for Analyze with AI
  onAnalyzeCode,
  problemDescription,
  examples,
  constraints,
  optimalComplexity
}) {
  // Initialize code with function signature if available
  const initialCode = functionSignature
    ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
    : DEFAULT_JAVA_TEMPLATE;
    
  const [code, setCode] = useState(initialCode);
  const [stdin, setStdin] = useState('');
  const [activeTab, setActiveTab] = useState('console');
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');
  const [timedOut, setTimedOut] = useState(false);
  
  // Cooldown State
  const [cooldown, setCooldown] = useState(0);
  
  // Analyze with AI State
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  
  // Execution State (for analysis context)
  const [lastRunResult, setLastRunResult] = useState(null);

  useEffect(() => {
    let timer;
    if (cooldown > 0) {
      timer = setInterval(() => {
        setCooldown(prev => prev - 1);
      }, 1000);
    }
    return () => clearInterval(timer);
  }, [cooldown]);

  // Sync stdin with autoGeneratedInput prop
  useEffect(() => {
    if (autoGeneratedInput) {
      setStdin(autoGeneratedInput);
    }
  }, [autoGeneratedInput]);
  
  // Resizable panel state
  const [editorHeight, setEditorHeight] = useState(60); // percentage
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef(null);

  const handlePanelMouseMove = useCallback((e) => {
    if (!isDragging || !containerRef.current) return;
    const containerRect = containerRef.current.getBoundingClientRect();
    // Calculate new height as percentage relative to container
    // We are resizing the TOP panel (editor), so we use (mouseY - top)
    const relativeY = e.clientY - containerRect.top;
    let newHeight = (relativeY / containerRect.height) * 100;
    
    // Clamp between 20% and 80%
    newHeight = Math.max(20, Math.min(80, newHeight));
    setEditorHeight(newHeight);
  }, [isDragging]);

  const handlePanelMouseUp = useCallback(() => {
    setIsDragging(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  useEffect(() => {
    if (isDragging) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'row-resize';
      document.body.style.userSelect = 'none';
    }
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDragging, handlePanelMouseMove, handlePanelMouseUp]);

  // ... (Lines 39-100 preserved) ...

  const handleRunCode = async () => {
    if (cooldown > 0) return;

    setIsRunning(true);
    setOutput('');
    setError('');
    setTimedOut(false);

    try {
      console.log('Running code with stdin:', stdin);
      const result = await onRunCode(code, stdin, problemId);
      console.log('Code execution result:', result);
      
      if (result.timedOut) {
        setTimedOut(true);
        setOutput(result.stdout || '');
        setError(`Execution timed out after ${result.timeout || 3000}ms`);
        setLastRunResult({ success: false, error: 'Timed out', output: result.stdout });
      } else {
        // Capture all possible output fields
        const outputText = result.stdout || result.output || result.result || '';
        console.log('Setting output to:', outputText);
        setOutput(outputText);
        
        const hasError = !!result.stderr;
        if (hasError) {
          console.log('Setting error to:', result.stderr);
          setError(result.stderr);
        }
        
        // If both output and error are empty, show a message
        if (!outputText && !result.stderr && result.exitCode === 0) {
          setOutput('Code executed successfully with no output.');
        }

        setLastRunResult({ 
          success: !hasError && result.exitCode === 0, 
          error: result.stderr, 
          output: outputText 
        });
      }
      // Start cooldown ONLY after successful execution (to prevent punishing errors too hard?)
      // Actually user said "wait 30s between pressing buttons", implying attempts.
      setCooldown(30); 

    } catch (err) {
      console.error('Code execution error:', err);
      setError(err.message || 'Failed to execute code');
    } finally {
      setIsRunning(false);
    }
  };

  const handleReset = () => {
    const resetCode = functionSignature
      ? `import java.util.*;\n\nclass Solution {\n    ${functionSignature} {\n        // Write your code here\n        \n    }\n}`
      : DEFAULT_JAVA_TEMPLATE;
      
    setCode(resetCode);
    setStdin(autoGeneratedInput || ''); // Sync back to auto-generated instead of empty
    setOutput('');
    setError('');
    setTimedOut(false);
    setLastRunResult(null); // Reset run state
    setAnalysisResult(null); // Clear analysis
  };

  const handleAnalyzeCode = async () => {
    if (!onAnalyzeCode || isAnalyzing) return;
    
    setIsAnalyzing(true);
    setActiveTab('analysis');
    
    try {
      // Pass code AND the last execution result to the analysis function
      const result = await onAnalyzeCode(code, lastRunResult);
      setAnalysisResult(result);
    } catch (err) {
      console.error('Analysis failed:', err);
      setAnalysisResult({ error: err.message || 'Analysis failed' });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const tabs = [
    { id: 'console', label: 'Output' },
    { id: 'input', label: 'Input' },
    { id: 'edgecases', label: 'Edge Cases', badge: edgeCases?.length || 0 },
    { id: 'analysis', label: 'Analysis', badge: analysisResult ? 'done' : null }
  ];

  return (
    <div ref={containerRef} className="h-full flex flex-col bg-dark-950 border-l border-dark-800 overflow-hidden relative">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-dark-800 bg-dark-950/80 backdrop-blur-md shrink-0 z-10">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-dark-500 uppercase tracking-wider">Language</span>
            <div className="px-2 py-1 bg-brand-orange/10 text-brand-orange rounded text-xs font-bold border border-brand-orange/20 flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-brand-orange animate-pulse"></span>
              Java
            </div>
          </div>
          
          <div className="w-px h-4 bg-dark-800 mx-2"></div>
          
          {/* Timer */}
          <Timer autoStart={true} />
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleReset}
            className="p-2 text-dark-400 hover:text-white hover:bg-dark-800 rounded-lg transition-colors group"
            title="Reset to default template"
          >
            <RotateCcw className="w-4 h-4 group-hover:-rotate-90 transition-transform duration-500" />
          </button>
          <button
            onClick={handleRunCode}
            disabled={isRunning || cooldown > 0}
            className="px-4 py-1.5 bg-brand-orange hover:bg-orange-600 disabled:bg-dark-800 disabled:text-dark-500 text-white rounded-lg font-bold text-xs transition-all flex items-center gap-2 disabled:cursor-not-allowed shadow-lg shadow-brand-orange/20 disabled:shadow-none hover:scale-105 active:scale-95"
          >
            {isRunning ? (
              <>
                <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                Running...
              </>
            ) : cooldown > 0 ? (
              <>
                <div className="w-3 h-3 text-dark-500"><Clock className="w-full h-full" /></div>
                Wait {cooldown}s
              </>
            ) : (
              <>
                <Play className="w-3 h-3 fill-current" />
                Run Code
              </>
            )}
          </button>
          
          {/* Analyze with AI Button */}
          {onAnalyzeCode && (
            <button
              onClick={handleAnalyzeCode}
              disabled={isAnalyzing || !lastRunResult}
              title={!lastRunResult ? "Run your code first to enable analysis" : "Analyze code with AI"}
              className="px-4 py-1.5 bg-purple-600 hover:bg-purple-500 disabled:bg-dark-800 disabled:text-dark-500 text-white rounded-lg font-bold text-xs transition-all flex items-center gap-2 disabled:cursor-not-allowed shadow-lg shadow-purple-600/20 disabled:shadow-none hover:scale-105 active:scale-95"
            >
              {isAnalyzing ? (
                <>
                  <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                  Analyzing...
                </>
              ) : (
                <>
                  <Brain className="w-3 h-3" />
                  Analyze with AI
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {/* Code Editor - Resizable */}
      <div 
        className="min-h-0 overflow-hidden relative"
        style={{ height: `${editorHeight}%` }}
      >
        <CodeEditor value={code} onChange={setCode} language="java" />
      </div>

      {/* Draggable Divider */}
      <div 
        className="h-3 bg-dark-950 border-y border-dark-800 cursor-row-resize flex items-center justify-center hover:bg-dark-900 transition-colors shrink-0 group z-10"
        onMouseDown={() => setIsDragging(true)}
      >
        <div className="w-12 h-1 rounded-full bg-dark-800 group-hover:bg-brand-orange/50 transition-colors"></div>
      </div>

      {/* Bottom Panel with Tabs - Resizable */}
      <div 
        className="flex flex-col min-h-0 overflow-hidden bg-dark-900/30"
        style={{ height: `${100 - editorHeight}%` }}
      >
        {/* Tab Headers */}
        <div className="flex items-center border-b border-dark-800 bg-dark-950/50 backdrop-blur shrink-0 px-2 pt-2 gap-1">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-t-lg transition-all border-t border-x ${
                activeTab === tab.id
                  ? 'border-dark-800 bg-dark-900 text-white border-b-transparent translate-y-px'
                  : 'border-transparent text-dark-500 hover:text-dark-300 hover:bg-dark-800/50'
              }`}
            >
              {tab.label}
              {tab.badge !== undefined && tab.badge > 0 && (
                <span className="ml-2 px-1.5 py-0.5 bg-brand-orange/20 text-brand-orange text-[10px] rounded-full">
                  {tab.badge}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="flex-1 min-h-0 overflow-hidden bg-dark-900 p-2">
          <div className="h-full rounded-lg border border-dark-800 bg-dark-950/50 overflow-hidden">
            {activeTab === 'console' && (
              <ConsolePanel 
                output={output} 
                error={error} 
                timedOut={timedOut} 
                isLoading={isRunning} 
                testCases={edgeCases}
              />
            )}
            {activeTab === 'input' && (
              <InputPanel value={stdin} onChange={setStdin} />
            )}
            {activeTab === 'edgecases' && (
              <EdgeCasesPanel
                edgeCases={edgeCases}
                isGenerating={isGeneratingEdgeCases}
                onGenerate={onGenerateEdgeCases}
                onCopyInput={(input) => setStdin(input)}
              />
            )}
            {activeTab === 'analysis' && (
              <AnalysisPanel 
                result={analysisResult} 
                isLoading={isAnalyzing}
                onClear={() => setAnalysisResult(null)}
              />
            )}
          </div>
        </div>
      </div>


    </div>
  );
}

CodePanel.propTypes = {
  problemId: PropTypes.string.isRequired,
  onRunCode: PropTypes.func.isRequired,
  edgeCases: PropTypes.array,
  onGenerateEdgeCases: PropTypes.func,
  isGeneratingEdgeCases: PropTypes.bool,
  autoGeneratedInput: PropTypes.string,
  functionSignature: PropTypes.string,
  // New props for Analyze with AI
  onAnalyzeCode: PropTypes.func,
  problemDescription: PropTypes.string,
  examples: PropTypes.array,
  constraints: PropTypes.array,
  optimalComplexity: PropTypes.object
};

export default CodePanel;

// ============================================================
// Analysis Panel Component
// ============================================================
function AnalysisPanel({ result, isLoading, onClear }) {
  if (isLoading) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-dark-400 p-8">
        <div className="relative">
          <Cpu className="w-12 h-12 text-purple-500 animate-pulse" />
          <Zap className="w-4 h-4 text-purple-400 absolute -top-1 -right-1 animate-bounce" />
        </div>
        <p className="mt-4 font-bold">Analyzing your code...</p>
        <p className="text-xs text-dark-500 mt-1">Evaluating complexity, quality, and patterns</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-dark-400 p-8">
        <Brain className="w-10 h-10 text-dark-600 mb-3" />
        <p className="font-bold">No Analysis Yet</p>
        <p className="text-xs text-dark-500 mt-1">Click "Analyze with AI" to get feedback on your code</p>
      </div>
    );
  }

  if (result.error) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-red-400 p-8">
        <AlertTriangle className="w-10 h-10 mb-3" />
        <p className="font-bold">Analysis Failed</p>
        <p className="text-xs text-dark-400 mt-1">{result.error}</p>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto p-4 space-y-4 no-scrollbar">
      {/* Header with Clear Button */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-black text-white uppercase tracking-wider flex items-center gap-2">
          <Brain className="w-4 h-4 text-purple-400" />
          AI Analysis
        </h3>
        <button 
          onClick={onClear}
          className="p-1 text-dark-500 hover:text-white hover:bg-dark-800 rounded transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Summary */}
      {result.summary && (
        <div className="p-3 bg-purple-500/10 border border-purple-500/20 rounded-lg">
          <p className="text-sm text-purple-300">{result.summary}</p>
        </div>
      )}

      {/* Complexity Cards */}
      <div className="grid grid-cols-2 gap-3">
        <div className="p-3 bg-dark-800/50 border border-dark-700 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-blue-400" />
            <span className="text-xs font-bold text-dark-400 uppercase">Time</span>
          </div>
          <p className="text-lg font-black text-white">{result.timeComplexity?.value || 'N/A'}</p>
          <p className="text-xs text-dark-400 mt-1">{result.timeComplexity?.explanation}</p>
        </div>
        <div className="p-3 bg-dark-800/50 border border-dark-700 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-green-400" />
            <span className="text-xs font-bold text-dark-400 uppercase">Space</span>
          </div>
          <p className="text-lg font-black text-white">{result.spaceComplexity?.value || 'N/A'}</p>
          <p className="text-xs text-dark-400 mt-1">{result.spaceComplexity?.explanation}</p>
        </div>
      </div>

      {/* Code Quality */}
      {result.codeQuality && (
        <div className="p-3 bg-dark-800/50 border border-dark-700 rounded-lg">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold text-dark-400 uppercase">Code Quality</span>
            <span className={`text-lg font-black ${result.codeQuality.score >= 7 ? 'text-green-400' : result.codeQuality.score >= 5 ? 'text-yellow-400' : 'text-red-400'}`}>
              {result.codeQuality.score}/10
            </span>
          </div>
          <p className="text-sm text-dark-300">{result.codeQuality.summary}</p>
        </div>
      )}

      {/* Key Insights */}
      {result.keyInsights?.length > 0 && (
        <div className="space-y-2">
          <h4 className="text-xs font-bold text-green-400 uppercase tracking-wider flex items-center gap-2">
            <CheckCircle className="w-3.5 h-3.5" />
            What You Did Well
          </h4>
          <div className="space-y-2">
            {result.keyInsights.map((insight, idx) => (
              <div key={idx} className="p-2 bg-green-500/10 border border-green-500/20 rounded-lg text-sm text-green-300">
                {insight}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Improvements - Only shown if present */}
      {result.improvements && (
        <div className="space-y-2">
          <h4 className="text-xs font-bold text-yellow-400 uppercase tracking-wider flex items-center gap-2">
            <Lightbulb className="w-3.5 h-3.5" />
            Room for Improvement
          </h4>
          {result.improvements.suggestions?.map((suggestion, idx) => (
            <div key={idx} className="p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg space-y-1">
              <p className="text-sm font-bold text-yellow-300">{suggestion.issue}</p>
              <p className="text-xs text-dark-300">{suggestion.impact}</p>
              {suggestion.fix && (
                <div className="mt-2 p-2 bg-dark-950 rounded text-xs text-dark-200 font-mono whitespace-pre-wrap">
                  {suggestion.fix}
                </div>
              )}
            </div>
          ))}
          {result.improvements.betterApproach && (
            <div className="p-3 bg-blue-500/10 border border-blue-500/20 rounded-lg">
              <p className="text-xs font-bold text-blue-400 uppercase mb-1">Better Approach</p>
              <p className="text-sm text-blue-300">{result.improvements.betterApproach}</p>
            </div>
          )}
        </div>
      )}

      {/* Tips for 10/10 - Only shown if score < 10 and tips exist */}
      {result.codeQuality.score < 10 && result.improvementTips?.length > 0 && (
        <div className="space-y-2">
          <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-2">
            <Star className="w-3.5 h-3.5" />
            Tips for a Perfect 10
          </h4>
          <div className="space-y-2">
            {result.improvementTips.map((tip, idx) => (
              <div key={idx} className="p-2 bg-indigo-500/10 border border-indigo-500/20 rounded-lg text-sm text-indigo-300 flex items-start gap-2">
                <span className="mt-1 w-1 h-1 rounded-full bg-indigo-400 shrink-0" />
                <span>{tip}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

