import { useState, useEffect, useRef, useCallback } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Zap, ExternalLink, Cpu, ChevronRight, Eye, EyeOff, Lightbulb, Terminal, GripVertical } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';


function AIInterviewPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(location.state?.problem || null);

  // Load problem from localStorage if ID is present in URL
  // Load problem from localStorage if ID is present in URL
  const [loadingProblem, setLoadingProblem] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const localId = params.get('localId');
    
    if (localId && !problem) {
      const checkStorage = () => {
        try {
          const storedData = localStorage.getItem(`ai_problem_${localId}`);
          if (storedData) {
            setProblem(JSON.parse(storedData));
            // Clean up localStorage after reading to prevent stale data
            localStorage.removeItem(`ai_problem_${localId}`);
            return true;
          }
        } catch (err) {
          console.error('Failed to load problem from storage:', err);
        }
        return false;
      };

      // Check immediately
      if (checkStorage()) return;

      // If not found, start polling
      setLoadingProblem(true);
      const intervalId = setInterval(() => {
        if (checkStorage()) {
          clearInterval(intervalId);
          setLoadingProblem(false);
        }
      }, 500);

      // Timeout after 120 seconds (2 minutes)
      const timeoutId = setTimeout(() => {
        clearInterval(intervalId);
        setLoadingProblem(false);
        if (!problem) {
          console.error('Timed out waiting for problem data. LocalId:', localId);
        }
      }, 120000);

      return () => {
        clearInterval(intervalId);
        clearTimeout(timeoutId);
      };
    }
  }, [location.search, problem]);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('optimal');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50); // percentage
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);

  // Hydrate state from problem data if it contains full AI package
  useEffect(() => {
    if (problem) {
      if (problem.solutions || problem.hints) {
        setHelpData({
          hints: problem.hints || [],
          solutions: problem.solutions || {}
        });
      }
      
      if (problem.edgeCases) {
        setEdgeCases(problem.edgeCases);
        if (problem.edgeCases.length > 0) {
          const jsonTestFormat = convertEdgeCasesToJsonFormat(problem.edgeCases, problem);
          setAutoGeneratedInput(jsonTestFormat);
        }
      }
    }
  }, [problem]);

  // Auto-fetch AI content on load for AI-generated problems
  useEffect(() => {
    // Trigger if no helpData or if solutions are missing/empty
    const needsContent = !helpData || !helpData.solutions?.optimal;
    if (problem && needsContent && !loadingEdgeCases && !loadingHelp) {
      handleFetchAIContent();
    }
  }, [problem]);

  // Handle mouse move for panel resizing
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    
    const container = containerRef.current;
    const containerRect = container.getBoundingClientRect();
    const mouseX = e.clientX - containerRect.left;
    
    let newWidth = (mouseX / containerRect.width) * 100;
    newWidth = Math.max(25, Math.min(75, newWidth));
    
    setLeftPanelWidth(newWidth);
  }, [isDraggingPanel]);

  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    }
    
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const handleAIAssist = async (forceRefresh = false) => {
    if (helpData?.solutions?.optimal && !forceRefresh) {
      return; 
    }
    // Mode 'full' generates everything
    await handleFetchAIContent({ forceRefresh, mode: 'full' });
  };

  const handleGenerateEdgeCases = async () => {
    // Mode 'edge_cases_only' generates only edge cases (using provided solution for computation)
    await handleFetchAIContent({ 
      forceRefresh: true, 
      mode: 'edge_cases_only',
      providedSolution: helpData?.solutions?.optimal?.code || null
    });
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      // Use a generic ID or the title for AI problems
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId || 'ai-generated'
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  // Handle Analyze with AI
  const handleAnalyzeCode = async (code, executionFeedback) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const optimalComplexity = helpData?.solutions?.optimal?.complexity || null;
      
      const response = await api.post('/ai/analyze-code', {
        code,
        problemDescription: problem?.description || problem?.title || '',
        examples: problem?.examples || [],
        constraints: problem?.constraints || [],
        optimalComplexity,
        executionFeedback
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      return response.data;
    } catch (error) {
      console.error('Failed to analyze code:', error);
      throw new Error(error.response?.data?.error || 'Failed to analyze code');
    }
  };

  const handleFetchAIContent = async (options = {}) => {
    // Backward compatibility for boolean argument
    const config = typeof options === 'boolean' ? { forceRefresh: options } : options;
    const { forceRefresh = false, mode = 'full', providedSolution = null } = config;

    if ((loadingEdgeCases || loadingHelp) && !forceRefresh) return;
    if (!problem) return;

    try {
      if (mode === 'full') {
        setLoadingEdgeCases(true);
        setLoadingHelp(true);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(true);
      }

      const token = await auth.currentUser.getIdToken();
      
      const response = await api.post('/ai/problem-help', {
        title: problem.title,
        description: problem.description,
        difficulty: problem.difficulty,
        pattern: problem.pattern || null,
        examples: problem.examples || [],
        constraints: problem.constraints || [],
        functionSignature: problem.functionSignature || null,
        forceRefresh: forceRefresh,
        mode: mode,
        providedSolution: providedSolution,
        existingEdgeCases: edgeCases // Pass existing edge cases to avoid redundant generation
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });

      const data = response.data;

      // 1. Set Help Data (Hints & Solutions) - Only if generated
      if (data.hints?.length > 0 || data.solutions?.optimal) {
        setHelpData({
          hints: data.hints || [],
          solutions: data.solutions
        });
      }

      let generatedEdgeCases = data.edgeCases || [];
      
      // Normalize: ensure expectedOutput is set (backend might return 'expected')
      if (Array.isArray(generatedEdgeCases)) {
        generatedEdgeCases = generatedEdgeCases.map(tc => ({
          ...tc,
          expectedOutput: tc.expectedOutput ?? tc.expected ?? 'N/A'
        }));
      }

      if (generatedEdgeCases.length > 0) {
        setEdgeCases(generatedEdgeCases);
        
        // Auto-convert edge cases to JSON test format
        if (data.edgeCases.length > 0) {
          const jsonTestFormat = convertEdgeCasesToJsonFormat(data.edgeCases, problem);
          console.log('[EdgeCases] Converted Edge Cases for Console:', jsonTestFormat);
          setAutoGeneratedInput(jsonTestFormat);
        } else {
          console.warn('[EdgeCases] Edge cases array is empty!');
        }
      } else {
        console.warn('[EdgeCases] No edgeCases field in API response:', data);
      }

    } catch (error) {
      console.error('Failed to fetch AI content:', error);
      if (forceRefresh) alert('Failed to regenerate content.');
    } finally {
      if (mode === 'full') {
        setLoadingEdgeCases(false);
        setLoadingHelp(false);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(false);
      }
    }
  };

  // Parse function signature to extract parameter names
  const parseParamNames = (signature) => {
    if (!signature) return [];
    try {
      // Extract content between parentheses: "int[] nums, int target"
      const match = signature.match(/\((.*?)\)/);
      if (!match || !match[1]) return [];
      
      return match[1].split(',').map(param => {
        // "int[] nums" -> ["int[]", "nums"]
        const parts = param.trim().split(/\s+/);
        return parts[parts.length - 1]; // Last part is usually the name
      });
    } catch (e) {
      console.warn('Failed to parse function signature params:', e);
      return [];
    }
  };

  // Helper function to convert edge cases to JSON test format
  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    const methodName = getMethodName(problem.title, problem.functionSignature);
    const paramNames = parseParamNames(problem.functionSignature);

    const tests = edgeCases.map(edgeCase => {
    // 1. If 'args' already exists from the backend, use it directly!
    // This avoids the 'triple nesting' bug where we re-wrap already wrapped args.
    if (edgeCase.args && Array.isArray(edgeCase.args)) {
      return {
        args: edgeCase.args,
        expected: edgeCase.expected || edgeCase.expectedOutput
      };
    }

    let args = [];
    const input = edgeCase.input;

    // Logic to map input object to ordered args array
    if (paramNames.length > 0 && typeof input === 'object' && input !== null && !Array.isArray(input)) {
      // Map keys to param names in order
      args = paramNames.map(name => {
        // Try exact match
        if (input[name] !== undefined) return input[name];
        // Try case-insensitive match
        const key = Object.keys(input).find(k => k.toLowerCase() === name.toLowerCase());
        return key ? input[key] : null; 
      });
      
      // If mapping seemingly failed (all nulls) or input has keys not matching params, 
      // fallback to just values if the counts match
      const validArgs = args.filter(a => a !== null);
      if (validArgs.length === 0 && Object.keys(input).length > 0) {
         args = Object.values(input);
      }
    } else {
      // Fallback for array or primitive input
      // If we know there is exactly 1 parameter and input is an array, wrap it!
      if (paramNames.length === 1 && Array.isArray(input)) {
         args = [input];
      } else {
         args = parseInputToArgs(input);
      }
    }
    
    return {
      args: args,
      expected: edgeCase.expected || edgeCase.expectedOutput
    };
  });

    return JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
  };

  // Extract method name from function signature or infer from title
  const getMethodName = (title, functionSignature) => {
    // 1. Try to extract from function signature
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) {
        return match[1];
      }
    }

    // 2. Fallback: infer from title
    return inferMethodNameFromTitle(title);
  };

  // Infer method name from problem title (Fallback)
  const inferMethodNameFromTitle = (title) => {
    if (!title) return 'solve';
    
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  // Convert raw input to args array
  const parseInputToArgs = (input) => {
    // Smart wrapping: if it looks like a single array argument (list of primitives), wrap it.
    if (Array.isArray(input)) {
       const isPrimitiveList = input.every(i => typeof i === 'number' || typeof i === 'string' || typeof i === 'boolean');
       if (isPrimitiveList) return [input];
       return input;
    }
    if (typeof input === 'object' && input !== null) return Object.values(input); 
    return [input];
  };

  if (loadingProblem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange mb-4"></div>
        <h2 className="text-xl font-bold text-white mb-2">Generating Interview Problem...</h2>
        <p className="text-dark-400">Our AI is crafting a unique challenge for you.</p>
      </div>
    );
  }

  if (!problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center text-dark-300">
        <p className="mb-4">No problem data found.</p>
        <button 
          onClick={() => navigate('/revision')}
          className="px-4 py-2 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          Go Back
        </button>
      </div>
    );
  }

  return (
    <div ref={containerRef} className="h-screen bg-dark-950 text-dark-100 flex overflow-hidden">
      {/* Left Column - Problem Description */}
      <div 
        className="h-full flex flex-col border-r border-dark-800"
        style={{ width: `${leftPanelWidth}%` }}
      >
        {/* Left Header */}
        {/* Left Header */}
        <div className="relative flex items-center justify-between px-4 py-3 border-b border-dark-800 bg-dark-900 shrink-0">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => navigate('/revision')}
              className="p-1.5 hover:bg-dark-800 rounded transition-colors text-dark-400 hover:text-white"
              title="Exit Session"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-base font-bold text-white">{problem.title}</h1>
              <div className="flex items-center gap-1.5 mt-0.5">
                <span className="px-2 py-0.5 rounded text-sm font-bold bg-brand-orange/10 text-brand-orange flex items-center gap-1">
                  <Zap className="w-3 h-3" /> AI GENERATED
                </span>
                <span className={`px-2 py-0.5 rounded text-sm font-bold ${
                  problem.difficulty === 'Easy' ? 'bg-green-500/10 text-green-400' :
                  problem.difficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400' :
                  'bg-red-500/10 text-red-400'
                }`}>
                  {problem.difficulty}
                </span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-4 relative z-20">
            {(!helpData || !helpData.solutions) && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp}
                className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Cpu className="w-4 h-4" />
                )}
                AI Assist
              </button>
            )}
          </div>
        </div>

        {/* Left Content */}
        <div className="flex-1 overflow-y-auto p-3 space-y-3 no-scrollbar">
          {/* Description */}
          <div className="bg-dark-900 p-5 rounded-xl border border-dark-800">
            <h2 className="text-[1.15rem] font-[800] text-white mb-4">Description</h2>
            <div className="prose prose-invert max-w-none text-dark-200 text-[1.1rem] font-[450] leading-relaxed">
              <ReactMarkdown>{typeof problem.description === 'object' ? JSON.stringify(problem.description) : problem.description}</ReactMarkdown>
            </div>
            
            {/* Function Signature */}
            {problem.functionSignature && (
              <div className="mt-6 p-4 bg-dark-950 rounded-lg border border-dark-800">
                <p className="text-[14px] font-[500] text-dark-400 mb-2">Function Signature:</p>
                <code className="text-base text-green-400 font-mono font-[500]">{typeof problem.functionSignature === 'object' ? JSON.stringify(problem.functionSignature) : problem.functionSignature}</code>
              </div>
            )}
          </div>

          {/* Examples */}
          {problem.examples && problem.examples.length > 0 && (
            <div className="space-y-4">
              <h2 className="text-[1.3rem] font-[800] text-white">Examples</h2>
              <div className="grid gap-4">
                {problem.examples.map((example, index) => (
                  <div key={index} className="bg-dark-900 rounded-lg p-5 border border-dark-800">
                    <div className="space-y-3 font-mono text-base font-[500]">
                      <div>
                        <span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                      </div>
                      <div>
                        <span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                      </div>
                      {example.explanation && (
                        <div className="pt-3 text-dark-200 font-sans text-[14.5px] font-[450] leading-relaxed">
                          <span className="text-dark-400 font-[800] uppercase tracking-wider block mb-1.5">Explanation:</span>
                          <ReactMarkdown components={{
                            p: ({node, ...props}) => <span {...props} />,
                            code: ({node, ...props}) => <code className="bg-dark-800 px-1.5 py-0.5 rounded text-brand-orange font-bold" {...props} />
                          }}>
                            {example.explanation}
                          </ReactMarkdown>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Constraints */}
          {problem.constraints && problem.constraints.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-[1.3rem] font-[800] text-white">Constraints</h2>
              </div>
              <ul className="list-disc list-inside space-y-2 text-dark-200 bg-dark-900 p-5 rounded-lg border border-dark-800 text-[1.1rem] font-[450]">
                {problem.constraints.map((constraint, index) => (
                  <li key={index}>{constraint}</li>
                ))}
              </ul>
            </div>
          )}

          {/* AI Assist Section */}
          {helpData && (
            <div className="space-y-6 pt-6 border-t border-dark-800">
              {/* Hints Section */}
              {helpData.hints && helpData.hints.length > 0 && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white flex items-center gap-2">
                      <Lightbulb className="w-5 h-5 text-yellow-400" /> Hints
                    </h2>
                    <span className="text-sm text-dark-400">
                      {currentHintIndex + 1} / {helpData.hints.length} Revealed
                    </span>
                  </div>
                  
                  <div className="space-y-2">
                    {helpData.hints.slice(0, currentHintIndex + 1).map((hint, index) => (
                      <div key={index} className="bg-dark-900/50 border border-dark-700 rounded-lg p-3 text-dark-200 text-sm">
                        <span className="font-bold text-brand-orange mr-2">Hint {index + 1}:</span>
                        {hint}
                      </div>
                    ))}
                  </div>

                  {currentHintIndex < helpData.hints.length - 1 && (
                    <button
                      onClick={() => setCurrentHintIndex(prev => prev + 1)}
                      className="text-sm text-blue-400 hover:text-blue-300 font-medium flex items-center gap-1"
                    >
                      Show Next Hint <ChevronRight className="w-4 h-4" />
                    </button>
                  )}
                </div>
              )}

              {/* Solutions Section */}
              {helpData.solutions && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white flex items-center gap-2">
                      <Cpu className="w-5 h-5 text-green-400" /> Solution
                    </h2>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setShowSolution(!showSolution);
                      }}
                      className="flex items-center gap-2 text-sm font-medium px-3 py-1.5 rounded-lg bg-dark-800 hover:bg-dark-700 text-dark-200 transition-colors"
                    >
                      {showSolution ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      {showSolution ? 'Hide Solution' : 'Show Solution'}
                    </button>
                  </div>

                  {showSolution && (
                    <div className="bg-dark-900 border border-dark-800 rounded-lg overflow-hidden">
                      {/* Solution Tabs */}
                      <div className="flex border-b border-dark-800">
                        {['optimal', 'better', 'brute'].map((tab) => (
                          helpData.solutions[tab] && (
                            <button
                              key={tab}
                              onClick={() => setActiveSolutionTab(tab)}
                              className={`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${
                                activeSolutionTab === tab
                                  ? 'border-brand-orange text-white bg-dark-800/50'
                                  : 'border-transparent text-dark-400 hover:text-dark-200 hover:bg-dark-800/30'
                              }`}
                            >
                              {tab.charAt(0).toUpperCase() + tab.slice(1)}
                            </button>
                          )
                        ))}
                      </div>

                      {/* Solution Content */}
                      <div className="p-4 space-y-4">
                        {helpData.solutions[activeSolutionTab] ? (
                          <>
                            {/* Complexity Section */}
                            <div className="flex gap-4">
                              <div>
                                <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Time Complexity</h4>
                                <p className="text-emerald-400 font-mono text-sm bg-dark-950 inline-block px-2 py-1 rounded border border-dark-800">
                                  {helpData.solutions[activeSolutionTab].timeComplexity || helpData.solutions[activeSolutionTab].complexity || 'N/A'}
                                </p>
                              </div>
                              <div>
                                <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Space Complexity</h4>
                                <p className="text-blue-400 font-mono text-sm bg-dark-950 inline-block px-2 py-1 rounded border border-dark-800">
                                  {helpData.solutions[activeSolutionTab].spaceComplexity || 'N/A'}
                                </p>
                              </div>
                            </div>

                             {/* Intuition & Logic */}
                             {(helpData.solutions[activeSolutionTab].intuition || helpData.solutions[activeSolutionTab].explanation || helpData.solutions[activeSolutionTab].approach) && (
                               <div>
                                <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest mb-2">Intuition & Pattern</h4>
                                <p className="text-dark-200 leading-relaxed text-xs bg-brand-orange/5 p-3 rounded-r border-l-2 border-brand-orange">
                                  {helpData.solutions[activeSolutionTab].intuition || helpData.solutions[activeSolutionTab].explanation || helpData.solutions[activeSolutionTab].approach}
                                </p>
                               </div>
                             )}
 
                             {/* Approach Steps */}
                             {helpData.solutions[activeSolutionTab].approachSteps?.length > 0 && (
                               <div>
                                <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest mb-3">Wait... How it works? (Step-by-Step)</h4>
                                <div className="space-y-3">
                                  {helpData.solutions[activeSolutionTab].approachSteps.map((step, i) => (
                                    <div key={i} className="flex gap-4 text-[13.5px] font-medium group">
                                      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-dark-800 border border-dark-700 flex items-center justify-center text-[10px] font-bold text-brand-orange group-hover:border-brand-orange/50 transition-colors shadow-sm">
                                        {i + 1}
                                      </span>
                                      <p className="text-dark-100 pt-0.5 leading-relaxed">
                                        {step.replace(/^\w+\s+\d+:\s*/, '')}
                                      </p>
                                    </div>
                                  ))}
                                </div>
                               </div>
                             )}

                            {/* Code with Syntax Highlighting */}
                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Code (Java)</h4>
                              <div className="rounded-lg overflow-hidden border border-dark-800">
                                <SyntaxHighlighter
                                  language="java"
                                  style={vscDarkPlus}
                                  customStyle={{ margin: 0, padding: '1rem', fontSize: '0.75rem', background: '#0d1117' }}
                                  showLineNumbers={true}
                                  wrapLines={true}
                                >
                                  {typeof helpData.solutions[activeSolutionTab].code === 'object' 
                                    ? JSON.stringify(helpData.solutions[activeSolutionTab].code, null, 2) 
                                    : helpData.solutions[activeSolutionTab].code || '// No code available'}
                                </SyntaxHighlighter>
                              </div>
                            </div>
                          </>
                        ) : (
                          <div className="text-center py-4">
                            <p className="text-dark-400 italic text-sm mb-3">No specific {activeSolutionTab} approach available.</p>
                            {activeSolutionTab === 'optimal' && (
                              <button
                                onClick={() => handleAIAssist(true)}
                                disabled={loadingHelp}
                                className="px-4 py-2 bg-brand-orange hover:bg-brand-orange/80 text-white rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 mx-auto"
                              >
                                {loadingHelp ? (
                                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                ) : (
                                  <Terminal className="w-4 h-4" />
                                )}
                                Regenerate Solution
                              </button>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Draggable Vertical Divider */}
      <div 
        className="w-1.5 h-full bg-dark-800 cursor-col-resize flex items-center justify-center hover:bg-dark-700 transition-colors shrink-0 group"
        onMouseDown={() => setIsDraggingPanel(true)}
      >
        <GripVertical className="w-3 h-3 text-dark-500 group-hover:text-dark-300" />
      </div>

      {/* Right Column - Code Editor (Full Height) */}
      <div 
        className="h-full"
        style={{ width: `${100 - leftPanelWidth}%` }}
      >
        <CodePanel
          problemId={problem.title}
          onRunCode={handleRunCode}
          edgeCases={edgeCases}
          onGenerateEdgeCases={handleGenerateEdgeCases}
          isGeneratingEdgeCases={loadingEdgeCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={problem.functionSignature}
          onAnalyzeCode={handleAnalyzeCode}
          problemDescription={problem?.description}
          examples={problem?.examples}
          constraints={problem?.constraints}
          optimalComplexity={helpData?.solutions?.optimal?.complexity}
        />
      </div>
      


    </div>
  );
}

export default AIInterviewPage;
