import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Zap, ExternalLink, Bot, ChevronRight, Eye, EyeOff, Lightbulb, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';

function AIInterviewPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(location.state?.problem || null);

  // Load problem from localStorage if ID is present in URL
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const localId = params.get('localId');
    
    if (localId && !problem) {
      try {
        const storedData = localStorage.getItem(`ai_problem_${localId}`);
        if (storedData) {
          setProblem(JSON.parse(storedData));
          // Optional: Clear storage after loading to keep it clean
          // localStorage.removeItem(`ai_problem_${localId}`);
        }
      } catch (err) {
        console.error('Failed to load problem from storage:', err);
      }
    }
  }, [location.search, problem]);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('brute');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  // Initialize hints if available in problem data
  useEffect(() => {
    if (problem?.hints) {
      setHelpData(prev => ({
        ...prev,
        hints: problem.hints,
        solutions: prev?.solutions || {}
      }));
    }
  }, [problem]);

  // Auto-generate AI edge cases when problem loads
  useEffect(() => {
    if (problem && !edgeCases && !loadingEdgeCases) {
      handleGenerateEdgeCases();
    }
  }, [problem]);

  const handleAIAssist = async () => {
    if (helpData?.solutions?.brute) return; // Already fetched solutions

    try {
      setLoadingHelp(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-help', {
        title: problem.title,
        description: problem.description,
        difficulty: problem.difficulty
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      // Merge with existing hints if any
      setHelpData(prev => ({
        hints: prev?.hints || response.data.hints,
        solutions: response.data.solutions
      }));
    } catch (error) {
      console.error('Failed to get AI help:', error);
      alert('Failed to generate AI solutions.');
    } finally {
      setLoadingHelp(false);
    }
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      // Use a generic ID or the title for AI problems
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId || 'ai-generated'
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  const handleGenerateEdgeCases = async () => {
    if (loadingEdgeCases || !problem) return;

    try {
      setLoadingEdgeCases(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/edge-cases', {
        title: problem.title,
        description: problem.description,
        examples: problem.examples || [],
        constraints: problem.constraints || [],
        functionSignature: problem.functionSignature || null
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const generatedEdgeCases = response.data;
      setEdgeCases(generatedEdgeCases);
      
      // Auto-convert edge cases to JSON test format
      if (generatedEdgeCases && generatedEdgeCases.length > 0) {
        const jsonTestFormat = convertEdgeCasesToJsonFormat(generatedEdgeCases, problem);
        setAutoGeneratedInput(jsonTestFormat);
      }
    } catch (error) {
      console.error('Failed to generate edge cases:', error);
      if (!edgeCases) {
        console.warn('Auto edge case generation failed');
      }
    } finally {
      setLoadingEdgeCases(false);
    }
  };

  // Helper function to convert edge cases to JSON test format
  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    const methodName = inferMethodName(problem.title);
    
    const tests = edgeCases.map(edgeCase => {
      const args = parseInputToArgs(edgeCase.input);
      const expected = edgeCase.expectedOutput;
      
      return {
        args: args,
        expected: expected
      };
    });

    return JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
  };

  // Infer method name from problem title
  const inferMethodName = (title) => {
    if (!title) return 'solve';
    
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  // Parse input string to arguments array
  const parseInputToArgs = (input) => {
    if (Array.isArray(input)) return input;
    if (typeof input === 'object' && input !== null) return [input];
    
    if (typeof input === 'string') {
      const trimmed = input.trim();
      if (trimmed.includes('=')) {
        const parts = trimmed.split(/,\s*(?![^\[\]]*\])/);
        const args = [];
        for (const part of parts) {
          if (part.includes('=')) {
            const value = part.split('=')[1].trim();
            try { args.push(JSON.parse(value)); } catch (e) { args.push(value); }
          } else {
            try { args.push(JSON.parse(part.trim())); } catch (e) { args.push(part.trim()); }
          }
        }
        return args;
      }
      try {
        const parsed = JSON.parse(trimmed);
        return Array.isArray(parsed) ? parsed : [parsed];
      } catch (e) {
        try { return JSON.parse(`[${trimmed}]`); } catch (e2) { return [input]; }
      }
    }
    return [input];
  };

  if (!problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center text-dark-300">
        <p className="mb-4">No problem data found.</p>
        <button 
          onClick={() => navigate('/revision')}
          className="px-4 py-2 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          Go Back
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-dark-950 text-dark-100 flex flex-col">
      {/* Header */}
      <div className="border-b border-dark-800 bg-dark-900 sticky top-0 z-10">
        <div className="max-w-screen-2xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => navigate('/revision')}
              className="p-2 hover:bg-dark-800 rounded-full transition-colors text-dark-400 hover:text-white"
              title="Exit Session"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-xl font-bold text-white">{problem.title}</h1>
              <div className="flex items-center gap-2 mt-1">
                <span className="px-2 py-0.5 rounded text-xs font-bold bg-brand-orange/10 text-brand-orange border border-brand-orange/20 flex items-center gap-1">
                  <Zap className="w-3 h-3" /> AI GENERATED
                </span>
                <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                  problem.difficulty === 'Easy' ? 'bg-green-500/10 text-green-400 border border-green-500/20' :
                  problem.difficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/20' :
                  'bg-red-500/10 text-red-400 border border-red-500/20'
                }`}>
                  {problem.difficulty}
                </span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {(!helpData || !helpData.solutions) && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp}
                className="px-3 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors flex items-center gap-2 text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Bot className="w-4 h-4" />
                )}
                AI Assist
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Two-Column Layout */}
      <div className="flex-1 max-w-screen-2xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-0">
        {/* Left Column - Problem Description */}
        <div className="h-[calc(100vh-73px)] overflow-y-auto border-r border-dark-800 p-6 space-y-6 no-scrollbar">
          {/* Description */}
          <div className="bg-dark-900 p-6 rounded-xl border border-dark-800">
            <h2 className="text-lg font-bold text-white mb-4">Description</h2>
            <div className="prose prose-invert max-w-none text-dark-300">
              <ReactMarkdown>{problem.description}</ReactMarkdown>
            </div>
            
            {/* Function Signature */}
            {problem.functionSignature && (
              <div className="mt-4 p-3 bg-dark-950 rounded-lg border border-dark-800">
                <p className="text-xs text-dark-400 mb-1">Function Signature:</p>
                <code className="text-sm text-green-400 font-mono">{problem.functionSignature}</code>
              </div>
            )}
          </div>

          {/* Examples */}
          {problem.examples && problem.examples.length > 0 && (
            <div className="space-y-3">
              <h2 className="text-lg font-bold text-white">Examples</h2>
              <div className="grid gap-3">
                {problem.examples.map((example, index) => (
                  <div key={index} className="bg-dark-900 rounded-lg p-4 border border-dark-800">
                    <div className="space-y-2 font-mono text-sm">
                      <div>
                        <span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                      </div>
                      <div>
                        <span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                      </div>
                      {example.explanation && (
                        <div className="pt-2 text-dark-300 font-sans text-xs">
                          <span className="text-dark-500 font-bold uppercase tracking-wider block mb-1">Explanation:</span>
                          <ReactMarkdown components={{
                            p: ({node, ...props}) => <span {...props} />,
                            code: ({node, ...props}) => <code className="bg-dark-800 px-1 py-0.5 rounded text-brand-orange" {...props} />
                          }}>
                            {example.explanation}
                          </ReactMarkdown>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Constraints */}
          {problem.constraints && problem.constraints.length > 0 && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-bold text-white">Constraints</h2>
                <button
                  onClick={handleGenerateEdgeCases}
                  disabled={loadingEdgeCases}
                  className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 disabled:bg-dark-700 text-white rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 disabled:cursor-not-allowed"
                  title="Generate additional edge cases using AI (optional)"
                >
                  {loadingEdgeCases ? (
                    <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  ) : (
                    <Sparkles className="w-3 h-3" />
                  )}
                  AI Edge Cases
                </button>
              </div>
              <ul className="list-disc list-inside space-y-1.5 text-dark-300 bg-dark-900 p-4 rounded-lg border border-dark-800 text-sm">
                {problem.constraints.map((constraint, index) => (
                  <li key={index}>{constraint}</li>
                ))}
              </ul>
            </div>
          )}

          {/* AI Assist Section */}
          {helpData && (
            <div className="space-y-6 pt-6 border-t border-dark-800">
              {/* Hints Section */}
              {helpData.hints && helpData.hints.length > 0 && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white flex items-center gap-2">
                      <Lightbulb className="w-5 h-5 text-yellow-400" /> Hints
                    </h2>
                    <span className="text-sm text-dark-400">
                      {currentHintIndex + 1} / {helpData.hints.length} Revealed
                    </span>
                  </div>
                  
                  <div className="space-y-2">
                    {helpData.hints.slice(0, currentHintIndex + 1).map((hint, index) => (
                      <div key={index} className="bg-dark-900/50 border border-dark-700 rounded-lg p-3 text-dark-200 text-sm">
                        <span className="font-bold text-brand-orange mr-2">Hint {index + 1}:</span>
                        {hint}
                      </div>
                    ))}
                  </div>

                  {currentHintIndex < helpData.hints.length - 1 && (
                    <button
                      onClick={() => setCurrentHintIndex(prev => prev + 1)}
                      className="text-sm text-blue-400 hover:text-blue-300 font-medium flex items-center gap-1"
                    >
                      Show Next Hint <ChevronRight className="w-4 h-4" />
                    </button>
                  )}
                </div>
              )}

              {/* Solutions Section */}
              {helpData.solutions && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white flex items-center gap-2">
                      <Bot className="w-5 h-5 text-green-400" /> Solution
                    </h2>
                    <button
                      onClick={() => setShowSolution(!showSolution)}
                      className="flex items-center gap-2 text-sm font-medium px-3 py-1.5 rounded-lg bg-dark-800 hover:bg-dark-700 text-dark-200 transition-colors"
                    >
                      {showSolution ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      {showSolution ? 'Hide Solution' : 'Show Solution'}
                    </button>
                  </div>

                  {showSolution && (
                    <div className="bg-dark-900 border border-dark-800 rounded-lg overflow-hidden">
                      {/* Solution Tabs */}
                      <div className="flex border-b border-dark-800">
                        {['brute', 'better', 'optimal'].map((tab) => (
                          helpData.solutions[tab] && (
                            <button
                              key={tab}
                              onClick={() => setActiveSolutionTab(tab)}
                              className={`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${
                                activeSolutionTab === tab
                                  ? 'border-brand-orange text-white bg-dark-800/50'
                                  : 'border-transparent text-dark-400 hover:text-dark-200 hover:bg-dark-800/30'
                              }`}
                            >
                              {tab.charAt(0).toUpperCase() + tab.slice(1)}
                            </button>
                          )
                        ))}
                      </div>

                      {/* Solution Content */}
                      <div className="p-4 space-y-4">
                        {helpData.solutions[activeSolutionTab] ? (
                          <>
                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Complexity</h4>
                              <p className="text-white font-mono text-sm bg-dark-950 inline-block px-2 py-1 rounded border border-dark-800">
                                {helpData.solutions[activeSolutionTab].complexity}
                              </p>
                            </div>
                            
                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Explanation</h4>
                              <p className="text-dark-200 leading-relaxed text-sm">
                                {helpData.solutions[activeSolutionTab].explanation}
                              </p>
                            </div>

                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Code (Java)</h4>
                              <div className="bg-dark-950 rounded-lg p-3 border border-dark-800 overflow-x-auto">
                                <pre className="text-xs font-mono text-blue-300">
                                  <code>{helpData.solutions[activeSolutionTab].code}</code>
                                </pre>
                              </div>
                            </div>
                          </>
                        ) : (
                          <p className="text-dark-400 italic text-sm">No specific {activeSolutionTab} approach available.</p>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Right Column - Code Editor */}
        <div className="h-[calc(100vh-73px)] p-6 bg-dark-950">
          <CodePanel
            problemId={problem.title} // Use title as ID for AI problems
            onRunCode={handleRunCode}
            edgeCases={edgeCases}
            onGenerateEdgeCases={handleGenerateEdgeCases}
            isGeneratingEdgeCases={loadingEdgeCases}
            autoGeneratedInput={autoGeneratedInput}
            functionSignature={problem.functionSignature}
          />
        </div>
      </div>
    </div>
  );
}

export default AIInterviewPage;
