import { useState, useEffect, useRef, useCallback } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Zap, ExternalLink, Cpu, ChevronRight, Eye, EyeOff, Lightbulb, Terminal, GripVertical } from 'lucide-react';
import SafeMarkdown from '../components/ui/SafeMarkdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';
import WorkspaceSolutionView from '../components/features/ai/WorkspaceSolutionView';
import ProgressiveHints from '../components/features/ai/ProgressiveHints';


function AIInterviewPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(location.state?.problem || null);

  // Track whether we're still waiting for problem data from localStorage
  const [loadingProblem, setLoadingProblem] = useState(false);

  // Safety: If problem is set, ALWAYS clear the loading screen.
  // Why: There is a race condition where setProblem() and setLoadingProblem(false) are called together
  // in the interval callback, but React's useEffect cleanup can interfere because 'problem' is a
  // dependency. This separate effect guarantees loading is cleared no matter how problem was set.
  useEffect(() => {
    if (problem && loadingProblem) {
      setLoadingProblem(false);
    }
  }, [problem, loadingProblem]);

  // What: useEffect that polls localStorage for problem data (set by the source page after API call).
  // Why: The AI Interview tab opens before the API finishes, so we poll until data arrives.
  // How: Check localStorage every 500ms, timeout after 60 seconds if no data found.
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const localId = params.get('localId');
    
    // Only poll if we have a localId and NO problem data yet
    if (!localId || problem) return;

    const checkStorage = () => {
      try {
        const storedData = localStorage.getItem(`ai_problem_${localId}`);
        if (storedData) {
          setProblem(JSON.parse(storedData));
          // Clean up localStorage after reading to prevent stale data
          localStorage.removeItem(`ai_problem_${localId}`);
          return true;
        }
      } catch (err) {
        console.error('Failed to load problem from storage:', err);
      }
      return false;
    };

    // Check immediately — if data is already there, no need to wait
    if (checkStorage()) return;

    // Listen for storage events (fired instantly when data is written in another tab/window)
    const handleStorageChange = (e) => {
      if (e.key === `ai_problem_${localId}`) {
        checkStorage();
      }
    };
    window.addEventListener('storage', handleStorageChange);

    // Fallback: check once more after a brief grace period (1.5s) then stop loading
    const timerId = setTimeout(() => {
      checkStorage();
      setLoadingProblem(false);
    }, 1500);

    return () => {
      window.removeEventListener('storage', handleStorageChange);
      clearTimeout(timerId);
    };
  }, [location.search]);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('optimal');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  // Ref to prevent duplicate description fetch calls
  // Why: Without this, the useEffect can fire handleFetchAIContent multiple times
  // while we're still waiting for the description to come back from the API
  const fetchingDescriptionRef = useRef(false);

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50); // percentage
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);

  // Hydrate state from problem data if it contains full AI package
  useEffect(() => {
    if (problem) {
      if (problem.solutions || problem.hints) {
        setHelpData({
          hints: problem.hints || [],
          solutions: problem.solutions || {}
        });
      }
      
      if (problem.edgeCases) {
        setEdgeCases(problem.edgeCases);
        if (problem.edgeCases.length > 0) {
          const jsonTestFormat = convertEdgeCasesToJsonFormat(problem.edgeCases, problem);
          setAutoGeneratedInput(jsonTestFormat);
        }
      }
    }
  }, [problem]);

  // Auto-fetch AI content on load for AI-generated problems
  useEffect(() => {
    // Trigger if no helpData or if solutions are missing/empty
    const needsContent = !helpData || !helpData.solutions?.optimal;
    if (problem && needsContent && !loadingEdgeCases && !loadingHelp) {
      handleFetchAIContent();
    }
  }, [problem]);

  // Handle mouse move for panel resizing
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    
    const container = containerRef.current;
    const containerRect = container.getBoundingClientRect();
    const mouseX = e.clientX - containerRect.left;
    
    let newWidth = (mouseX / containerRect.width) * 100;
    newWidth = Math.max(25, Math.min(75, newWidth));
    
    setLeftPanelWidth(newWidth);
  }, [isDraggingPanel]);

  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    }
    
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const handleAIAssist = async (forceRefresh = false) => {
    if (helpData?.solutions?.optimal && !forceRefresh) {
      return; 
    }
    // Mode 'full' generates everything
    await handleFetchAIContent({ forceRefresh, mode: 'full' });
  };

  const handleGenerateEdgeCases = async () => {
    // Mode 'edge_cases_only' generates only edge cases (using provided solution for computation)
    await handleFetchAIContent({ 
      forceRefresh: true, 
      mode: 'edge_cases_only',
      providedSolution: helpData?.solutions?.optimal?.code || null
    });
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      // Use a generic ID or the title for AI problems
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId || 'ai-generated'
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  // Handle Analyze with AI
  const handleAnalyzeCode = async (code, executionFeedback) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const optimalComplexity = helpData?.solutions?.optimal?.complexity || null;
      
      const response = await api.post('/ai/analyze-code', {
        code,
        problemDescription: problem?.description || problem?.title || '',
        examples: problem?.examples || [],
        constraints: problem?.constraints || [],
        optimalComplexity,
        executionFeedback
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      return response.data;
    } catch (error) {
      console.error('Failed to analyze code:', error);
      throw new Error(error.response?.data?.error || 'Failed to analyze code');
    }
  };

  const handleFetchAIContent = async (options = {}) => {
    // Backward compatibility for boolean argument
    const config = typeof options === 'boolean' ? { forceRefresh: options } : options;
    const { forceRefresh = false, mode = 'full', providedSolution = null } = config;

    if ((loadingEdgeCases || loadingHelp) && !forceRefresh) return;
    if (!problem) return;

    // Validate required fields before making API call
    // Why: The AI backend sometimes returns a problem object without a 'description' field.
    // What: If title exists but description is missing, we auto-fetch it from the description endpoint.
    // How: Call /ai/problem-description to generate the missing description, then update the problem state.
    if (!problem.title || !problem.description) {
      console.warn('Missing required fields:', { title: problem.title, description: problem.description });

      // If we have a title but no description, auto-generate it
      // Also check the ref to avoid duplicate calls while one is already in progress
      if (!problem.description && problem.title && !fetchingDescriptionRef.current) {
        console.log('Auto-generating missing problem description...');
        fetchingDescriptionRef.current = true; // Mark as in-progress
        try {
          const token = await auth.currentUser.getIdToken();

          // Fetch a description using the problem title from the AI description endpoint
          const descResponse = await api.post('/ai/problem-description', {
            title: problem.title,
            difficulty: problem.difficulty || 'Medium',
          }, {
            headers: { Authorization: `Bearer ${token}` }
          });

          // If we got a valid description back, update the problem state and continue
          if (descResponse.data?.description) {
            const updatedProblem = {
              ...problem,
              description: descResponse.data.description,
              // Also fill in any other missing fields from the response
              examples: problem.examples || descResponse.data.examples || [],
              constraints: problem.constraints || descResponse.data.constraints || [],
              functionSignature: problem.functionSignature || descResponse.data.functionSignature || null,
            };
            setProblem(updatedProblem);
            // Return here because setProblem will trigger the useEffect again
            // and re-call handleFetchAIContent with the updated problem
            return;
          }
        } catch (descError) {
          console.error('Failed to auto-generate description:', descError);
        } finally {
          fetchingDescriptionRef.current = false; // Reset regardless of success/failure
        }
      }

      // If we still can't get the required fields, bail out
      return;
    }

    try {
      if (mode === 'full') {
        setLoadingEdgeCases(true);
        setLoadingHelp(true);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(true);
      }

      const token = await auth.currentUser.getIdToken();
      
      const response = await api.post('/ai/problem-help', {
        title: problem.title,
        description: problem.description,
        difficulty: problem.difficulty,
        pattern: problem.pattern || null,
        examples: problem.examples || [],
        constraints: problem.constraints || [],
        functionSignature: problem.functionSignature || null,
        forceRefresh: forceRefresh,
        mode: mode,
        providedSolution: providedSolution,
        existingEdgeCases: edgeCases // Pass existing edge cases to avoid redundant generation
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });

      const data = response.data;

      // 1. Set Help Data (Hints & Solutions) - Only if generated
      if (data.hints?.length > 0 || data.solutions?.optimal) {
        setHelpData({
          hints: data.hints || [],
          solutions: data.solutions
        });
      }

      let generatedEdgeCases = data.edgeCases || [];
      
      // Normalize: ensure expectedOutput is set (backend might return 'expected')
      if (Array.isArray(generatedEdgeCases)) {
        generatedEdgeCases = generatedEdgeCases.map(tc => ({
          ...tc,
          expectedOutput: tc.expectedOutput ?? tc.expected ?? 'N/A'
        }));
      }

      if (generatedEdgeCases.length > 0) {
        setEdgeCases(generatedEdgeCases);
        
        // Auto-convert edge cases to JSON test format
        if (data.edgeCases.length > 0) {
          const jsonTestFormat = convertEdgeCasesToJsonFormat(data.edgeCases, problem);
          console.log('[EdgeCases] Converted Edge Cases for Console:', jsonTestFormat);
          setAutoGeneratedInput(jsonTestFormat);
        } else {
          console.warn('[EdgeCases] Edge cases array is empty!');
        }
      } else {
        console.warn('[EdgeCases] No edgeCases field in API response:', data);
      }

    } catch (error) {
      console.error('Failed to fetch AI content:', error);
      if (forceRefresh) alert('Failed to regenerate content.');
    } finally {
      if (mode === 'full') {
        setLoadingEdgeCases(false);
        setLoadingHelp(false);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(false);
      }
    }
  };

  // Parse function signature to extract parameter names
  const parseParamNames = (signature) => {
    if (!signature) return [];
    try {
      // Extract content between parentheses: "int[] nums, int target"
      const match = signature.match(/\((.*?)\)/);
      if (!match || !match[1]) return [];
      
      return match[1].split(',').map(param => {
        // "int[] nums" -> ["int[]", "nums"]
        const parts = param.trim().split(/\s+/);
        return parts[parts.length - 1]; // Last part is usually the name
      });
    } catch (e) {
      console.warn('Failed to parse function signature params:', e);
      return [];
    }
  };

  // Helper function to convert edge cases to JSON test format
  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    const methodName = getMethodName(problem.title, problem.functionSignature);
    const paramNames = parseParamNames(problem.functionSignature);

    const tests = edgeCases.map(edgeCase => {
    // 1. If 'args' already exists from the backend, use it directly!
    // This avoids the 'triple nesting' bug where we re-wrap already wrapped args.
    if (edgeCase.args && Array.isArray(edgeCase.args)) {
      return {
        args: edgeCase.args,
        expected: edgeCase.expected || edgeCase.expectedOutput
      };
    }

    let args = [];
    const input = edgeCase.input;

    // Logic to map input object to ordered args array
    if (paramNames.length > 0 && typeof input === 'object' && input !== null && !Array.isArray(input)) {
      // Map keys to param names in order
      args = paramNames.map(name => {
        // Try exact match
        if (input[name] !== undefined) return input[name];
        // Try case-insensitive match
        const key = Object.keys(input).find(k => k.toLowerCase() === name.toLowerCase());
        return key ? input[key] : null; 
      });
      
      // If mapping seemingly failed (all nulls) or input has keys not matching params, 
      // fallback to just values if the counts match
      const validArgs = args.filter(a => a !== null);
      if (validArgs.length === 0 && Object.keys(input).length > 0) {
         args = Object.values(input);
      }
    } else {
      // Fallback for array or primitive input
      // If we know there is exactly 1 parameter and input is an array, wrap it!
      if (paramNames.length === 1 && Array.isArray(input)) {
         args = [input];
      } else {
         args = parseInputToArgs(input);
      }
    }
    
    return {
      args: args,
      expected: edgeCase.expected || edgeCase.expectedOutput
    };
  });

    return JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
  };

  // Extract method name from function signature or infer from title
  const getMethodName = (title, functionSignature) => {
    // 1. Try to extract from function signature
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) {
        return match[1];
      }
    }

    // 2. Fallback: infer from title
    return inferMethodNameFromTitle(title);
  };

  // Infer method name from problem title (Fallback)
  const inferMethodNameFromTitle = (title) => {
    if (!title) return 'solve';
    
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  // Convert raw input to args array
  const parseInputToArgs = (input) => {
    // Smart wrapping: if it looks like a single array argument (list of primitives), wrap it.
    if (Array.isArray(input)) {
       const isPrimitiveList = input.every(i => typeof i === 'number' || typeof i === 'string' || typeof i === 'boolean');
       if (isPrimitiveList) return [input];
       return input;
    }
    if (typeof input === 'object' && input !== null) return Object.values(input); 
    return [input];
  };

  if (loadingProblem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange mb-4"></div>
        <h2 className="text-xl font-bold text-white mb-2">Generating Interview Problem...</h2>
        <p className="text-dark-400 mb-6">Our AI is crafting a unique challenge for you.</p>
        {/* Go back button so the user isn't stuck forever */}
        <button 
          onClick={() => navigate(-1)}
          className="px-4 py-2 bg-dark-800 rounded hover:bg-dark-700 transition-colors text-dark-300 text-sm"
        >
          ← Go Back
        </button>
      </div>
    );
  }

  if (!problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center text-dark-300">
        <p className="mb-4">No problem data found.</p>
        <button 
          onClick={() => navigate('/revision')}
          className="px-4 py-2 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          Go Back
        </button>
      </div>
    );
  }

  return (
    <div ref={containerRef} className="h-screen bg-dark-950 text-dark-100 flex overflow-hidden">
      {/* Left Column - Problem Description */}
      <div 
        className="h-full flex flex-col border-r border-dark-800"
        style={{ width: `${leftPanelWidth}%` }}
      >
        {/* Left Header */}
        {/* Left Header */}
        <div className="relative flex items-center justify-between px-4 py-3 border-b border-dark-800 bg-dark-900 shrink-0">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => navigate('/revision')}
              className="p-1.5 hover:bg-dark-800 rounded transition-colors text-dark-400 hover:text-white"
              title="Exit Session"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-base font-bold text-white">{problem.title}</h1>
              <div className="flex items-center gap-1.5 mt-0.5">
                <span className="px-2 py-0.5 rounded text-sm font-bold bg-brand-orange/10 text-brand-orange flex items-center gap-1">
                  <Zap className="w-3 h-3" /> AI GENERATED
                </span>
                <span className={`px-2 py-0.5 rounded text-sm font-bold ${
                  problem.difficulty === 'Easy' ? 'bg-green-500/10 text-green-400' :
                  problem.difficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400' :
                  'bg-red-500/10 text-red-400'
                }`}>
                  {problem.difficulty}
                </span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-4 relative z-20">
            {(!helpData || !helpData.solutions) && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp}
                className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Cpu className="w-4 h-4" />
                )}
                AI Assist
              </button>
            )}
          </div>
        </div>

        {/* Left Content */}
        <div className="flex-1 overflow-y-auto p-3 space-y-3 no-scrollbar">
          {/* Description */}
          <div className="bg-dark-900 p-5 rounded-xl border border-dark-800">
            <h2 className="text-[1.15rem] font-[800] text-white mb-4">Description</h2>
            <div className="prose prose-invert max-w-none text-dark-200 text-[1.1rem] font-[450] leading-relaxed">
              <SafeMarkdown>{typeof problem.description === 'object' ? JSON.stringify(problem.description) : problem.description}</SafeMarkdown>
            </div>
            
            {/* Function Signature */}
            {problem.functionSignature && (
              <div className="mt-6 p-4 bg-dark-950 rounded-lg border border-dark-800">
                <p className="text-[14px] font-[500] text-dark-400 mb-2">Function Signature:</p>
                <code className="text-base text-green-400 font-mono font-[500]">{typeof problem.functionSignature === 'object' ? JSON.stringify(problem.functionSignature) : problem.functionSignature}</code>
              </div>
            )}
          </div>

          {/* Examples */}
          {problem.examples && problem.examples.length > 0 && (
            <div className="space-y-4">
              <h2 className="text-[1.3rem] font-[800] text-white">Examples</h2>
              <div className="grid gap-4">
                {problem.examples.map((example, index) => (
                  <div key={index} className="bg-dark-900 rounded-lg p-5 border border-dark-800">
                    <div className="space-y-3 font-mono text-base font-[500]">
                      <div>
                        <span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                      </div>
                      <div>
                        <span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                      </div>
                      {example.explanation && (
                        <div className="pt-3 text-dark-200 font-sans text-[14.5px] font-[450] leading-relaxed">
                          <span className="text-dark-400 font-[800] uppercase tracking-wider block mb-1.5">Explanation:</span>
                          <SafeMarkdown components={{
                            p: ({node, ...props}) => <span {...props} />,
                            code: ({node, ...props}) => <code className="bg-dark-800 px-1.5 py-0.5 rounded text-brand-orange font-bold" {...props} />
                          }}>
                            {example.explanation}
                          </SafeMarkdown>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Constraints */}
          {problem.constraints && problem.constraints.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-[1.3rem] font-[800] text-white">Constraints</h2>
              </div>
              <ul className="list-disc list-inside space-y-2 text-dark-200 bg-dark-900 p-5 rounded-lg border border-dark-800 text-[1.1rem] font-[450]">
                {problem.constraints.map((constraint, index) => (
                  <li key={index}>{constraint}</li>
                ))}
              </ul>
            </div>
          )}

          {/* AI Assist Section */}
          {helpData && (
            <div className="space-y-6 pt-6 border-t border-dark-800">
              {/* Progressive Socratic Hints */}
              {helpData.hints && helpData.hints.length > 0 && (
                <ProgressiveHints hints={helpData.hints} />
              )}

              {/* Verified Solutions */}
              {helpData.solutions && (
                <div className="space-y-4 pt-4 border-t border-border">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Cpu className="w-4 h-4 text-primary" />
                      <h3 className="text-xs font-semibold text-foreground uppercase tracking-wider">
                        Verified Production Solution
                      </h3>
                    </div>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setShowSolution(!showSolution);
                      }}
                      className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-lg bg-surface-raised hover:bg-surface-hover text-foreground-muted hover:text-foreground border border-border transition-colors"
                    >
                      {showSolution ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                      {showSolution ? 'Hide Solution' : 'Reveal Solution'}
                    </button>
                  </div>

                  {showSolution && (
                    <WorkspaceSolutionView
                      solutions={helpData.solutions}
                      initialTier={activeSolutionTab}
                    />
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Draggable Vertical Divider */}
      <div 
        className="w-1.5 h-full bg-dark-800 cursor-col-resize flex items-center justify-center hover:bg-dark-700 transition-colors shrink-0 group"
        onMouseDown={() => setIsDraggingPanel(true)}
      >
        <GripVertical className="w-3 h-3 text-dark-500 group-hover:text-dark-300" />
      </div>

      {/* Right Column - Code Editor (Full Height) */}
      <div 
        className="h-full"
        style={{ width: `${100 - leftPanelWidth}%` }}
      >
        <CodePanel
          problemId={problem.title}
          onRunCode={handleRunCode}
          edgeCases={edgeCases}
          onGenerateEdgeCases={handleGenerateEdgeCases}
          isGeneratingEdgeCases={loadingEdgeCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={problem.functionSignature}
          onAnalyzeCode={handleAnalyzeCode}
          problemDescription={problem?.description}
          examples={problem?.examples}
          constraints={problem?.constraints}
          optimalComplexity={helpData?.solutions?.optimal?.complexity}
        />
      </div>
      


    </div>
  );
}

export default AIInterviewPage;
