import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Cpu, ChevronRight, Eye, EyeOff, Lightbulb, ExternalLink, Terminal, GripVertical } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';


function InterviewProblemPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  
  // Problem State
  const [problem, setProblem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Description State
  const [description, setDescription] = useState(null);
  const [loadingDescription, setLoadingDescription] = useState(false);

  // Test Cases State (auto-loads, independent)
  const [testCases, setTestCases] = useState(null);
  const [loadingTestCases, setLoadingTestCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');
  const testCasesGeneratedRef = useRef(false);

  // Solution State (on button click, completely independent)
  const [solutionData, setSolutionData] = useState(null);
  const [loadingSolution, setLoadingSolution] = useState(false);
  const [showSolution, setShowSolution] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50);
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);

  // Fetch problem on mount
  useEffect(() => {
    const fetchProblem = async () => {
      try {
        setLoading(true);
        const response = await api.get(`/revisions/${id}`);
        const data = response.data || response;
        setProblem(data);
        
        if (!data.description && data.problemTitle) {
          fetchDescription(data.problemTitle);
        } else if (data.description) {
          setDescription(data.description);
        } else {
          setDescription('Problem details unavailable.');
        }
      } catch (err) {
        console.error('Failed to fetch problem:', err);
        setError('Failed to load problem');
      } finally {
        setLoading(false);
      }
    };

    if (id) fetchProblem();
  }, [id]);

  // Auto-generate test cases when description loads (ONCE, independent)
  useEffect(() => {
    if (description && problem && !testCasesGeneratedRef.current && !loadingTestCases) {
      testCasesGeneratedRef.current = true;
      handleGenerateTestCases();
    }
  }, [description, problem]);

  // Panel resizing handlers
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    const containerRect = containerRef.current.getBoundingClientRect();
    let newWidth = ((e.clientX - containerRect.left) / containerRect.width) * 100;
    setLeftPanelWidth(Math.max(25, Math.min(75, newWidth)));
  }, [isDraggingPanel]);

  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    }
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const fetchDescription = async (title) => {
    try {
      setLoadingDescription(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-description', { title }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDescription(response.data);
    } catch (error) {
      console.error('Failed to fetch description:', error);
    } finally {
      setLoadingDescription(false);
    }
  };

  // ============================================================
  // INDEPENDENT: Generate Test Cases
  // ============================================================
  const handleGenerateTestCases = async () => {
    if (loadingTestCases || !description) return;

    try {
      setLoadingTestCases(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/test-cases', {
        title: problem.problemTitle,
        description: description.description || description,
        constraints: description.constraints || [],
        functionSignature: description.functionSignature || null,
        forceRefresh: true // Always get fresh test cases with computed expected values
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      const generatedTestCases = response.data;
      setTestCases(generatedTestCases);
      
      if (generatedTestCases && generatedTestCases.length > 0) {
        const jsonTestFormat = convertTestCasesToJsonFormat(generatedTestCases);
        setAutoGeneratedInput(jsonTestFormat);
      }
    } catch (error) {
      console.error('Failed to generate test cases:', error);
    } finally {
      setLoadingTestCases(false);
    }
  };

  // ============================================================
  // INDEPENDENT: Generate Solution (on button click only)
  // ============================================================
  const handleGetSolution = async (e) => {
    e.stopPropagation(); // Prevent any event bubbling
    if (loadingSolution || solutionData) return;

    try {
      setLoadingSolution(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/solution', {
        title: problem.problemTitle,
        description: description.description || description,
        difficulty: problem.difficulty || 'Medium',
        functionSignature: description.functionSignature || null,
        testCases: testCases || []
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      setSolutionData(response.data);
    } catch (error) {
      console.error('Failed to get solution:', error);
      alert('Failed to generate solution.');
    } finally {
      setLoadingSolution(false);
    }
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  // Handle Analyze with AI
  const handleAnalyzeCode = async (code, executionFeedback) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const optimalComplexity = solutionData?.solutions?.optimal?.complexity || null;
      
      const response = await api.post('/ai/analyze-code', {
        code,
        problemDescription: description?.description || problem?.problemTitle || '',
        examples: description?.examples || [],
        constraints: description?.constraints || [],
        optimalComplexity,
        executionFeedback
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      return response.data;
    } catch (error) {
      console.error('Failed to analyze code:', error);
      throw new Error(error.response?.data?.error || 'Failed to analyze code');
    }
  };

  const convertTestCasesToJsonFormat = (cases) => {
    const methodName = getMethodName(problem.problemTitle, description?.functionSignature);
    const tests = cases.map(tc => {
      // Priority 1: Use pre-formatted args if they exist to prevent triple-nesting
      if (tc.args && Array.isArray(tc.args)) {
        return {
          args: tc.args,
          expected: tc.expected || tc.expectedOutput
        };
      }
      // Priority 2: Use input and parse it
      return {
        args: parseInputToArgs(tc.input),
        expected: tc.expected || tc.expectedOutput
      };
    });
    return JSON.stringify({ method: methodName, tests }, null, 2);
  };

  const getMethodName = (title, functionSignature) => {
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) return match[1];
    }
    if (!title) return 'solve';
    return title.replace(/[^a-zA-Z0-9\s]/g, '').split(' ')
      .map((word, i) => i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  };

  const parseInputToArgs = (input) => {
    if (typeof input === 'object' && input !== null && !Array.isArray(input)) {
      return Object.values(input);
    }
    if (Array.isArray(input)) {
      const allPrimitives = input.every(i => typeof i === 'number' || typeof i === 'string' || typeof i === 'boolean');
      return allPrimitives ? [input] : input;
    }
    return [input];
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange"></div>
      </div>
    );
  }

  if (error || !problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center text-red-400">
        {error || 'Problem not found'}
      </div>
    );
  }

  return (
    <div ref={containerRef} className="h-screen bg-dark-950 text-dark-100 flex overflow-hidden">
      {/* Left Column - Problem Description */}
      <div className="h-full flex flex-col border-r border-dark-800" style={{ width: `${leftPanelWidth}%` }}>
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-dark-800 bg-dark-900 shrink-0">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => navigate('/revision')}
              className="p-1.5 hover:bg-dark-800 rounded transition-colors text-dark-400 hover:text-white"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-base font-bold text-white">{problem.problemTitle}</h1>
              <span className={`px-2 py-0.5 rounded text-sm font-bold ${
                (problem.difficulty || 'Medium') === 'Easy' ? 'bg-green-500/10 text-green-400' :
                (problem.difficulty || 'Medium') === 'Medium' ? 'bg-yellow-500/10 text-yellow-400' :
                'bg-red-500/10 text-red-400'
              }`}>
                {problem.difficulty || 'Medium'}
              </span>
            </div>
          </div>
          
          {/* Solution Button - Independent */}
          {!solutionData && (
            <button 
              type="button"
              onClick={handleGetSolution}
              disabled={loadingSolution || loadingDescription}
              className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
            >
              {loadingSolution ? (
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              ) : (
                <Cpu className="w-4 h-4" />
              )}
              Get Solution
            </button>
          )}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4 no-scrollbar">
          {loadingDescription ? (
            <div className="flex flex-col items-center justify-center py-12 text-dark-400">
              <div className="w-8 h-8 border-2 border-brand-orange/30 border-t-brand-orange rounded-full animate-spin mb-4" />
              <p>Fetching problem description...</p>
            </div>
          ) : description ? (
            <>
              {/* Description */}
              <div className="bg-dark-900 p-4 rounded-xl border border-dark-800">
                <h2 className="text-lg font-bold text-white mb-3">Description</h2>
                <div className="prose prose-invert max-w-none text-dark-300">
                  <ReactMarkdown>{typeof description === 'string' ? description : description.description}</ReactMarkdown>
                </div>
                {description.functionSignature && (
                  <div className="mt-4 p-3 bg-dark-950 rounded-lg border border-dark-800">
                    <p className="text-xs text-dark-400 mb-1">Function Signature:</p>
                    <code className="text-sm text-green-400 font-mono">{description.functionSignature}</code>
                  </div>
                )}
              </div>

              {/* Examples */}
              {description.examples?.length > 0 && (
                <div className="space-y-3">
                  <h2 className="text-lg font-bold text-white">Examples</h2>
                  {description.examples.map((example, index) => (
                    <div key={index} className="bg-dark-900 rounded-lg p-4 border border-dark-800 font-mono text-sm">
                      <div><span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span></div>
                      <div><span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span></div>
                      {example.explanation && <div className="pt-2 text-dark-300 font-sans text-xs">{example.explanation}</div>}
                    </div>
                  ))}
                </div>
              )}

              {/* Constraints with Test Cases Button */}
              {description.constraints?.length > 0 && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white">Constraints</h2>
                    <button
                      type="button"
                      onClick={(e) => { e.stopPropagation(); handleGenerateTestCases(); }}
                      disabled={loadingTestCases}
                      className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 disabled:bg-dark-700 text-white rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 disabled:cursor-not-allowed"
                    >
                      {loadingTestCases ? (
                        <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      ) : (
                        <Terminal className="w-3 h-3" />
                      )}
                      {testCases ? 'Regenerate' : 'Generate'} Test Cases
                    </button>
                  </div>
                  <ul className="list-disc list-inside space-y-1.5 text-dark-300 bg-dark-900 p-4 rounded-lg border border-dark-800 text-sm">
                    {description.constraints.map((constraint, index) => (
                      <li key={index}>{constraint}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* External Link */}
              {problem.problemLink && (
                <a 
                  href={problem.problemLink} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="px-3 py-2 bg-dark-800 hover:bg-dark-700 rounded-lg text-sm text-white transition-colors flex items-center gap-2 inline-flex"
                >
                  <ExternalLink className="w-4 h-4" /> Open Original Source
                </a>
              )}

              {/* Solution Section - Only shown after clicking Get Solution */}
              {solutionData && (
                <div className="space-y-4 pt-4 border-t border-dark-800">
                  {/* Hints */}
                  {solutionData.hints?.length > 0 && (
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                          <Lightbulb className="w-5 h-5 text-yellow-400" /> Hints
                        </h2>
                        <span className="text-sm text-dark-400">
                          {currentHintIndex + 1} / {solutionData.hints.length}
                        </span>
                      </div>
                      
                      <div className="space-y-2">
                        {solutionData.hints.slice(0, currentHintIndex + 1).map((hint, index) => (
                          <div key={index} className="bg-dark-900/50 border border-dark-700 rounded-lg p-3 text-dark-200 text-sm">
                            <span className="font-bold text-brand-orange mr-2">Hint {index + 1}:</span>
                            {hint}
                          </div>
                        ))}
                      </div>

                      {currentHintIndex < solutionData.hints.length - 1 && (
                        <button
                          type="button"
                          onClick={(e) => { e.stopPropagation(); setCurrentHintIndex(prev => prev + 1); }}
                          className="text-sm text-blue-400 hover:text-blue-300 font-medium flex items-center gap-1"
                        >
                          Show Next Hint <ChevronRight className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  )}

                  {/* Solution */}
                  {solutionData.solution && (
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <h2 className="text-lg font-bold text-white flex items-center gap-2">
                          <Cpu className="w-5 h-5 text-green-400" /> Solution
                        </h2>
                        <button
                          type="button"
                          onClick={(e) => { e.stopPropagation(); setShowSolution(!showSolution); }}
                          className="flex items-center gap-2 text-sm font-medium px-3 py-1.5 rounded-lg bg-dark-800 hover:bg-dark-700 text-dark-200 transition-colors"
                        >
                          {showSolution ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                          {showSolution ? 'Hide' : 'Show'} Solution
                        </button>
                      </div>

                      {showSolution && (
                        <div className="bg-dark-900 border border-dark-800 rounded-lg p-4 space-y-4">
                          {/* Approach */}
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Approach</h4>
                            <p className="text-dark-200 text-sm">{solutionData.solution.approach}</p>
                          </div>
                          
                          {/* Complexity */}
                          <div className="flex gap-4">
                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Time</h4>
                              <p className="text-green-400 font-mono text-sm">{solutionData.solution.timeComplexity}</p>
                            </div>
                            <div>
                              <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Space</h4>
                              <p className="text-blue-400 font-mono text-sm">{solutionData.solution.spaceComplexity}</p>
                            </div>
                          </div>

                          {/* Code */}
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Code (Java)</h4>
                            <div className="bg-dark-950 rounded-lg p-3 border border-dark-800 overflow-x-auto">
                              <pre className="text-xs font-mono text-blue-300">
                                <code>{solutionData.solution.code}</code>
                              </pre>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              )}
            </>
          ) : (
            <div className="bg-dark-900 rounded-lg p-6 border border-dark-800">
              <p className="text-dark-300 italic">Description unavailable.</p>
            </div>
          )}
        </div>
      </div>

      {/* Draggable Divider */}
      <div 
        className="w-1.5 h-full bg-dark-800 cursor-col-resize flex items-center justify-center hover:bg-dark-700 transition-colors shrink-0 group"
        onMouseDown={() => setIsDraggingPanel(true)}
      >
        <GripVertical className="w-3 h-3 text-dark-500 group-hover:text-dark-300" />
      </div>

      {/* Right Column - Code Editor */}
      <div className="h-full" style={{ width: `${100 - leftPanelWidth}%` }}>
        <CodePanel
          problemId={id}
          onRunCode={handleRunCode}
          edgeCases={testCases}
          onGenerateEdgeCases={handleGenerateTestCases}
          isGeneratingEdgeCases={loadingTestCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={description?.functionSignature}
          onAnalyzeCode={handleAnalyzeCode}
          problemDescription={description?.description}
          examples={description?.examples}
          constraints={description?.constraints}
          optimalComplexity={solutionData?.solutions?.optimal?.complexity}
        />
      </div>


    </div>
  );
}

export default InterviewProblemPage;
