import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Bot, ChevronRight, Eye, EyeOff, Lightbulb, ExternalLink, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';

function InterviewProblemPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Description State
  const [description, setDescription] = useState(null);
  const [loadingDescription, setLoadingDescription] = useState(false);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('brute');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  useEffect(() => {
    const fetchProblem = async () => {
      try {
        setLoading(true);
        const response = await api.get(`/revisions/${id}`);
        const data = response.data || response;
        console.log('Fetched problem data:', data);
        console.log('problemTitle:', data.problemTitle);
        console.log('description:', data.description);
        setProblem(data);
        
        // If description is missing, fetch it using AI
        if (!data.description && data.problemTitle) {
          fetchDescription(data.problemTitle);
        } else if (data.description) {
          setDescription(data.description);
        } else {
          console.warn('Problem has no title or description', data);
          setDescription('Problem details unavailable.');
        }
      } catch (err) {
        console.error('Failed to fetch problem:', err);
        setError('Failed to load problem');
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchProblem();
    }
  }, [id]);

  // Auto-generate AI edge cases when description loads (improved reliability)
  useEffect(() => {
    if (description && problem && !edgeCases && !loadingEdgeCases) {
      // Automatically generate comprehensive AI edge cases
      handleGenerateEdgeCases();
    }
  }, [description, problem]);

  const fetchDescription = async (title) => {
    try {
      setLoadingDescription(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-description', {
        title: title
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      // Response is now a full problem object with description, examples, constraints
      setDescription(response.data);
    } catch (error) {
      console.error('Failed to fetch description:', error);
    } finally {
      setLoadingDescription(false);
    }
  };

  const handleAIAssist = async () => {
    if (helpData) return;

    try {
      setLoadingHelp(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-help', {
        title: problem.problemTitle,
        description: description?.description || `Problem titled "${problem.problemTitle}"`,
        difficulty: problem.difficulty || 'Medium'
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setHelpData(response.data);
    } catch (error) {
      console.error('Failed to get AI help:', error);
      alert('Failed to generate AI hints and solutions.');
    } finally {
      setLoadingHelp(false);
    }
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  // Fast: Generate test cases from problem examples (no AI needed)
  const generateTestsFromExamples = (examples, problemTitle) => {
    if (!examples || examples.length === 0) {
      return null;
    }

    const methodName = getMethodName(problemTitle, description?.functionSignature);
    
    const tests = examples.map(example => {
      // Parse the example input and output
      const args = parseInputToArgs(example.input);
      const expected = example.output;
      
      return {
        args: args,
        expected: expected
      };
    });

    return JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
  };

  const handleGenerateEdgeCases = async () => {
    if (loadingEdgeCases || !description) return;

    try {
      setLoadingEdgeCases(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/edge-cases', {
        title: problem.problemTitle,
        description: description.description,
        examples: description.examples || [],
        constraints: description.constraints || [],
        functionSignature: description.functionSignature || null
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const generatedEdgeCases = response.data;
      setEdgeCases(generatedEdgeCases);
      
      // Auto-convert edge cases to JSON test format
      if (generatedEdgeCases && generatedEdgeCases.length > 0) {
        const jsonTestFormat = convertEdgeCasesToJsonFormat(generatedEdgeCases, problem);
        setAutoGeneratedInput(jsonTestFormat);
      }
    } catch (error) {
      console.error('Failed to generate edge cases:', error);
      // Don't alert for auto-generation failures, just log it
      if (!edgeCases) {
        console.warn('Auto edge case generation failed, user can manually trigger if needed');
      }
    } finally {
      setLoadingEdgeCases(false);
    }
  };

  // Helper function to convert edge cases to JSON test format
  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    // Try to infer method name from problem title or use a default
    const methodName = getMethodName(problem.problemTitle, description?.functionSignature);
    
    const tests = edgeCases.map(edgeCase => {
      // Parse input string to extract arguments
      const args = parseInputToArgs(edgeCase.input);
      const expected = edgeCase.expectedOutput;
      
      return {
        args: args,
        expected: expected
      };
    });

    return JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
  };

  // Extract method name from function signature or infer from title
  const getMethodName = (title, functionSignature) => {
    // 1. Try to extract from function signature
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) {
        return match[1];
      }
    }

    // 2. Fallback: infer from title
    return inferMethodNameFromTitle(title);
  };

  // Infer method name from problem title (Fallback)
  const inferMethodNameFromTitle = (title) => {
    if (!title) return 'solve';
    
    // Common LeetCode problem title patterns
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    // Default: camelCase the title
    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  // Parse input string to arguments array
  const parseInputToArgs = (input) => {
    // If input is already an array (from AI edge cases), return it directly
    if (Array.isArray(input)) {
      return input;
    }

    // If input is an object (and not null), wrap it in an array
    if (typeof input === 'object' && input !== null) {
      return [input];
    }
    
    // Handle string inputs
    if (typeof input === 'string') {
      const trimmed = input.trim();
      
      // Check if it's in LeetCode format like "nums = [2,7,11,15], target = 9"
      if (trimmed.includes('=')) {
        const parts = trimmed.split(/,\s*(?![^\[\]]*\])/); // Split by comma not inside brackets
        const args = [];
        
        for (const part of parts) {
          if (part.includes('=')) {
            // Extract value after '='
            const value = part.split('=')[1].trim();
            try {
              // Try to parse as JSON
              args.push(JSON.parse(value));
            } catch (e) {
              // If parsing fails, keep as string
              args.push(value);
            }
          } else {
            // No '=' found, try to parse the whole part
            try {
              args.push(JSON.parse(part.trim()));
            } catch (e) {
              args.push(part.trim());
            }
          }
        }
        
        return args;
      }
      
      // Try parsing as plain JSON
      try {
        const parsed = JSON.parse(trimmed);
        return Array.isArray(parsed) ? parsed : [parsed];
      } catch (e) {
        // Try wrapping in brackets
        try {
          return JSON.parse(`[${trimmed}]`);
        } catch (e2) {
          console.error('Failed to parse input:', input, e2);
          return [input]; // Return as-is wrapped in array
        }
      }
    }
    
    // If it's already a primitive, wrap it in array
    return [input];
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange"></div>
      </div>
    );
  }

  if (error || !problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center text-red-400">
        {error || 'Problem not found'}
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-dark-950 text-dark-100 flex flex-col">
      {/* Header */}
      <div className="border-b border-dark-800 bg-dark-900 sticky top-0 z-10">
        <div className="max-w-screen-2xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => navigate('/revision')}
              className="p-2 hover:bg-dark-800 rounded-full transition-colors text-dark-400 hover:text-white"
              title="Exit Session"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-xl font-bold text-white">{problem.problemTitle}</h1>
              <div className="flex items-center gap-2 mt-1">
                <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                  (problem.difficulty || 'Medium') === 'Easy' ? 'bg-green-500/10 text-green-400 border border-green-500/20' :
                  (problem.difficulty || 'Medium') === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/20' :
                  'bg-red-500/10 text-red-400 border border-red-500/20'
                }`}>
                  {problem.difficulty || 'Medium'}
                </span>
                <span className="text-dark-500 text-xs">Interview Practice</span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {!helpData && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp || loadingDescription}
                className="px-3 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors flex items-center gap-2 text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Bot className="w-4 h-4" />
                )}
                AI Assist
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Two-Column Layout */}
      <div className="flex-1 max-w-screen-2xl mx-auto w-full grid grid-cols-1 lg:grid-cols-2 gap-0">
        {/* Left Column - Problem Description */}
        <div className="h-[calc(100vh-73px)] overflow-y-auto border-r border-dark-800 p-6 space-y-6">
          {loadingDescription ? (
            <div className="flex flex-col items-center justify-center py-12 text-dark-400">
              <div className="w-8 h-8 border-2 border-brand-orange/30 border-t-brand-orange rounded-full animate-spin mb-4" />
              <p>Fetching problem description...</p>
            </div>
          ) : description ? (
            <>
              {/* Problem Description */}
              {/* Description */}
                  <div className="bg-dark-900 p-6 rounded-xl border border-dark-800">
                    <h2 className="text-lg font-bold text-white mb-4">Description</h2>
                    <div className="prose prose-invert max-w-none text-dark-300">
                      <ReactMarkdown>{description.description}</ReactMarkdown>
                    </div>
                    
                    {/* Function Signature */}
                    {description.functionSignature && (
                      <div className="mt-4 p-3 bg-dark-950 rounded-lg border border-dark-800">
                        <p className="text-xs text-dark-400 mb-1">Function Signature:</p>
                        <code className="text-sm text-green-400 font-mono">{description.functionSignature}</code>
                      </div>
                    )}
                  </div>

              {/* Examples */}
              {description.examples && description.examples.length > 0 && (
                <div className="space-y-3">
                  <h2 className="text-lg font-bold text-white">Examples</h2>
                  <div className="grid gap-3">
                    {description.examples.map((example, index) => (
                      <div key={index} className="bg-dark-900 rounded-lg p-4 border border-dark-800">
                        <div className="space-y-2 font-mono text-sm">
                          <div>
                            <span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                          </div>
                          <div>
                            <span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                          </div>
                          {example.explanation && (
                            <div className="pt-2 text-dark-300 font-sans text-xs">
                              <span className="text-dark-500 font-bold uppercase tracking-wider block mb-1">Explanation:</span>
                              <ReactMarkdown components={{
                                p: ({node, ...props}) => <span {...props} />,
                                code: ({node, ...props}) => <code className="bg-dark-800 px-1 py-0.5 rounded text-brand-orange" {...props} />
                              }}>
                                {example.explanation}
                              </ReactMarkdown>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Constraints */}
              {description.constraints && description.constraints.length > 0 && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white">Constraints</h2>
                    <button
                      onClick={handleGenerateEdgeCases}
                      disabled={loadingEdgeCases}
                      className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 disabled:bg-dark-700 text-white rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 disabled:cursor-not-allowed"
                      title="Generate additional edge cases using AI (optional)"
                    >
                      {loadingEdgeCases ? (
                        <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      ) : (
                        <Sparkles className="w-3 h-3" />
                      )}
                      AI Edge Cases
                    </button>
                  </div>
                  <ul className="list-disc list-inside space-y-1.5 text-dark-300 bg-dark-900 p-4 rounded-lg border border-dark-800 text-sm">
                    {description.constraints.map((constraint, index) => (
                      <li key={index}>{constraint}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Original Source Link */}
              <div className="pt-2">
                <a 
                  href={problem.problemLink} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="px-3 py-2 bg-dark-800 hover:bg-dark-700 rounded-lg text-sm text-white transition-colors flex items-center gap-2 border border-dark-700 inline-flex"
                >
                  <ExternalLink className="w-4 h-4" /> Open Original Source
                </a>
              </div>
            </>
          ) : (
            <div className="bg-dark-900 rounded-lg p-6 border border-dark-800">
              <p className="text-dark-300 italic">Description unavailable.</p>
            </div>
          )}

          {/* AI Assist Section - Now inside left column */}
          {helpData && (
            <div className="space-y-6 pt-6 border-t border-dark-800">
              
              {/* Hints Section */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-bold text-white flex items-center gap-2">
                    <Lightbulb className="w-5 h-5 text-yellow-400" /> Hints
                  </h2>
                  <span className="text-sm text-dark-400">
                    {currentHintIndex + 1} / {helpData.hints.length} Revealed
                  </span>
                </div>
                
                <div className="space-y-2">
                  {helpData.hints.slice(0, currentHintIndex + 1).map((hint, index) => (
                    <div key={index} className="bg-dark-900/50 border border-dark-700 rounded-lg p-3 text-dark-200 text-sm">
                      <span className="font-bold text-brand-orange mr-2">Hint {index + 1}:</span>
                      {hint}
                    </div>
                  ))}
                </div>

                {currentHintIndex < helpData.hints.length - 1 && (
                  <button
                    onClick={() => setCurrentHintIndex(prev => prev + 1)}
                    className="text-sm text-blue-400 hover:text-blue-300 font-medium flex items-center gap-1"
                  >
                    Show Next Hint <ChevronRight className="w-4 h-4" />
                  </button>
                )}
              </div>

              {/* Solutions Section */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-bold text-white flex items-center gap-2">
                    <Bot className="w-5 h-5 text-green-400" /> Solution
                  </h2>
                  <button
                    onClick={() => setShowSolution(!showSolution)}
                    className="flex items-center gap-2 text-sm font-medium px-3 py-1.5 rounded-lg bg-dark-800 hover:bg-dark-700 text-dark-200 transition-colors"
                  >
                    {showSolution ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    {showSolution ? 'Hide Solution' : 'Show Solution'}
                  </button>
                </div>

                {showSolution && (
                  <div className="bg-dark-900 border border-dark-800 rounded-lg overflow-hidden">
                    {/* Solution Tabs */}
                    <div className="flex border-b border-dark-800">
                      {['brute', 'better', 'optimal'].map((tab) => (
                        helpData.solutions[tab] && (
                          <button
                            key={tab}
                            onClick={() => setActiveSolutionTab(tab)}
                            className={`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${
                              activeSolutionTab === tab
                                ? 'border-brand-orange text-white bg-dark-800/50'
                                : 'border-transparent text-dark-400 hover:text-dark-200 hover:bg-dark-800/30'
                            }`}
                          >
                            {tab.charAt(0).toUpperCase() + tab.slice(1)}
                          </button>
                        )
                      ))}
                    </div>

                    {/* Solution Content */}
                    <div className="p-4 space-y-4">
                      {helpData.solutions[activeSolutionTab] ? (
                        <>
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Complexity</h4>
                            <p className="text-white font-mono text-sm bg-dark-950 inline-block px-2 py-1 rounded border border-dark-800">
                              {helpData.solutions[activeSolutionTab].complexity}
                            </p>
                          </div>
                          
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Explanation</h4>
                            <p className="text-dark-200 leading-relaxed text-sm">
                              {helpData.solutions[activeSolutionTab].explanation}
                            </p>
                          </div>

                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Code (Java)</h4>
                            <div className="bg-dark-950 rounded-lg p-3 border border-dark-800 overflow-x-auto">
                              <pre className="text-xs font-mono text-blue-300">
                                <code>{helpData.solutions[activeSolutionTab].code}</code>
                              </pre>
                            </div>
                          </div>
                        </>
                      ) : (
                        <p className="text-dark-400 italic text-sm">No specific {activeSolutionTab} approach available.</p>
                      )}
                    </div>
                  </div>
                )}
              </div>

            </div>
          )}
        </div>

        {/* Right Column - Code Editor */}
        <div className="h-[calc(100vh-73px)] p-6 bg-dark-950">
          <CodePanel
            problemId={id}
            onRunCode={handleRunCode}
            edgeCases={edgeCases}
            onGenerateEdgeCases={handleGenerateEdgeCases}
            isGeneratingEdgeCases={loadingEdgeCases}
            autoGeneratedInput={autoGeneratedInput}
            functionSignature={description?.functionSignature}
          />
        </div>
      </div>
    </div>
  );
}

export default InterviewProblemPage;
