import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Bot, ChevronRight, Eye, EyeOff, Lightbulb, ExternalLink, Sparkles, GripVertical } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';

function SolveProblemPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Description State
  const [description, setDescription] = useState(null);
  const [loadingDescription, setLoadingDescription] = useState(false);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('brute');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50); // percentage
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);

  useEffect(() => {
    const fetchProblem = async () => {
      try {
        setLoading(true);
        const response = await api.get(`/revisions/${id}`);
        const data = response.data || response;
        setProblem(data);
        
        // If description is missing, fetch it using AI
        if (!data.description && data.problemTitle) {
          fetchDescription(data.problemTitle);
        } else if (data.description) {
          setDescription(data.description);
        } else {
          setDescription('Problem details unavailable.');
        }
      } catch (err) {
        console.error('Failed to fetch problem:', err);
        setError('Failed to load problem');
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchProblem();
    }
  }, [id]);

  // Auto-generate AI edge cases when description loads
  useEffect(() => {
    if (description && problem && !edgeCases && !loadingEdgeCases) {
      handleGenerateEdgeCases();
    }
  }, [description, problem]);

  // Handle mouse move for panel resizing
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    
    const container = containerRef.current;
    const containerRect = container.getBoundingClientRect();
    const mouseX = e.clientX - containerRect.left;
    
    // Calculate percentage (clamp between 25% and 75%)
    let newWidth = (mouseX / containerRect.width) * 100;
    newWidth = Math.max(25, Math.min(75, newWidth));
    
    setLeftPanelWidth(newWidth);
  }, [isDraggingPanel]);

  // Handle mouse up to stop panel dragging
  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  // Add/remove global event listeners for panel dragging
  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    }
    
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const fetchDescription = async (title) => {
    try {
      setLoadingDescription(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-description', {
        title: title
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDescription(response.data);
    } catch (error) {
      console.error('Failed to fetch description:', error);
    } finally {
      setLoadingDescription(false);
    }
  };

  const handleAIAssist = async () => {
    if (helpData) return;

    try {
      setLoadingHelp(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-help', {
        title: problem.problemTitle,
        description: description?.description || `Problem titled "${problem.problemTitle}"`,
        difficulty: problem.difficulty || 'Medium'
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setHelpData(response.data);
    } catch (error) {
      console.error('Failed to get AI help:', error);
      alert('Failed to generate AI hints and solutions.');
    } finally {
      setLoadingHelp(false);
    }
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  const handleGenerateEdgeCases = async () => {
    if (loadingEdgeCases || !description) return;

    try {
      setLoadingEdgeCases(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/edge-cases', {
        title: problem.problemTitle,
        description: description.description || description,
        examples: description.examples || [],
        constraints: description.constraints || [],
        functionSignature: description.functionSignature || null
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const generatedEdgeCases = response.data;
      setEdgeCases(generatedEdgeCases);
      
      if (generatedEdgeCases && generatedEdgeCases.length > 0) {
        const jsonTestFormat = convertEdgeCasesToJsonFormat(generatedEdgeCases, problem);
        setAutoGeneratedInput(jsonTestFormat);
      }
    } catch (error) {
      console.error('Failed to generate edge cases:', error);
    } finally {
      setLoadingEdgeCases(false);
    }
  };

  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    // At this point, description should be loaded (we only generate edge cases after description loads)
    // Use description.functionSignature directly if available
    const methodName = getMethodName(problem.problemTitle, description?.functionSignature);
    
    console.log('Converting edge cases to JSON format...');
    console.log('Method name extracted:', methodName);
    console.log('Function signature:', description?.functionSignature);
    
    const tests = edgeCases.map(edgeCase => {
      const args = parseInputToArgs(edgeCase.input);
      const expected = edgeCase.expectedOutput;
      
      return {
        args: args,
        expected: expected
      };
    });

    const jsonResult = JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
    
    console.log('Generated JSON input (first 500 chars):', jsonResult.substring(0, 500));
    return jsonResult;
  };

  const getMethodName = (title, functionSignature) => {
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) {
        return match[1];
      }
    }
    return inferMethodNameFromTitle(title);
  };

  const inferMethodNameFromTitle = (title) => {
    if (!title) return 'solve';
    
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  const parseInputToArgs = (input) => {
    if (Array.isArray(input)) return input;
    if (typeof input === 'object' && input !== null) return [input];
    
    if (typeof input === 'string') {
      const trimmed = input.trim();
      if (trimmed.includes('=')) {
        const parts = trimmed.split(/,\s*(?![^\[\]]*\])/);
        const args = [];
        for (const part of parts) {
          if (part.includes('=')) {
            const value = part.split('=')[1].trim();
            try { args.push(JSON.parse(value)); } catch (e) { args.push(value); }
          } else {
            try { args.push(JSON.parse(part.trim())); } catch (e) { args.push(part.trim()); }
          }
        }
        return args;
      }
      try {
        const parsed = JSON.parse(trimmed);
        return Array.isArray(parsed) ? parsed : [parsed];
      } catch (e) {
        try { return JSON.parse(`[${trimmed}]`); } catch (e2) { return [input]; }
      }
    }
    return [input];
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange"></div>
      </div>
    );
  }

  if (error || !problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center text-red-400">
        {error || 'Problem not found'}
      </div>
    );
  }

  return (
    <div ref={containerRef} className="h-screen bg-dark-950 text-dark-100 flex overflow-hidden">
      {/* Left Column - Problem Description */}
      <div 
        className="h-full flex flex-col border-r border-dark-800"
        style={{ width: `${leftPanelWidth}%` }}
      >
        {/* Left Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-dark-800 bg-dark-900 shrink-0">
          <div className="flex items-center gap-3">
            <button 
              onClick={() => navigate('/revision')}
              className="p-1.5 hover:bg-dark-800 rounded transition-colors text-dark-400 hover:text-white"
              title="Back to Revision"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-base font-bold text-white">{problem.problemTitle}</h1>
              <div className="flex items-center gap-1.5 mt-0.5">
                <span className={`px-2 py-0.5 rounded text-sm font-bold ${
                  (problem.difficulty || 'Medium') === 'Easy' ? 'bg-green-500/10 text-green-400' :
                  (problem.difficulty || 'Medium') === 'Medium' ? 'bg-yellow-500/10 text-yellow-400' :
                  'bg-red-500/10 text-red-400'
                }`}>
                  {problem.difficulty || 'Medium'}
                </span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {!helpData && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp || loadingDescription}
                className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Bot className="w-4 h-4" />
                )}
                AI Assist
              </button>
            )}
          </div>
        </div>

        {/* Left Content */}
        <div className="flex-1 overflow-y-auto p-3 space-y-3 no-scrollbar">
          {loadingDescription ? (
            <div className="flex flex-col items-center justify-center py-12 text-dark-400">
              <div className="w-8 h-8 border-2 border-brand-orange/30 border-t-brand-orange rounded-full animate-spin mb-4" />
              <p>Fetching problem description...</p>
            </div>
          ) : description ? (
            <>
              {/* Description */}
              <div className="bg-dark-900 p-3 rounded-lg border border-dark-800">
                <h2 className="text-base font-bold text-white mb-2">Description</h2>
                <div className="prose prose-invert max-w-none text-dark-300">
                  <ReactMarkdown>{typeof description === 'string' ? description : description.description}</ReactMarkdown>
                </div>
                
                {/* Function Signature */}
                {description.functionSignature && (
                  <div className="mt-3 p-2 bg-dark-950 rounded border border-dark-800">
                    <p className="text-sm font-medium text-dark-400 mb-1">Function Signature:</p>
                    <code className="text-sm text-green-400 font-mono">{description.functionSignature}</code>
                  </div>
                )}
              </div>

              {/* Examples */}
              {description.examples && description.examples.length > 0 && (
                <div className="space-y-2">
                  <h2 className="text-base font-bold text-white">Examples</h2>
                  <div className="grid gap-2">
                    {description.examples.map((example, index) => (
                      <div key={index} className="bg-dark-900 rounded-lg p-3 border border-dark-800">
                        <div className="space-y-1.5 font-mono text-sm">
                          <div>
                            <span className="text-dark-400 font-medium">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                          </div>
                          <div>
                            <span className="text-dark-400 font-medium">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                          </div>
                          {example.explanation && (
                            <div className="pt-1.5 text-dark-300 font-sans text-sm">
                              <span className="text-dark-500 font-bold uppercase tracking-wider block mb-1">Explanation:</span>
                              <ReactMarkdown components={{
                                p: ({node, ...props}) => <span {...props} />,
                                code: ({node, ...props}) => <code className="bg-dark-800 px-1 py-0.5 rounded text-brand-orange" {...props} />
                              }}>
                                {example.explanation}
                              </ReactMarkdown>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Constraints */}
              {description.constraints && description.constraints.length > 0 && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <h2 className="text-base font-bold text-white">Constraints</h2>
                    <button
                      onClick={handleGenerateEdgeCases}
                      disabled={loadingEdgeCases}
                      className="px-2 py-1 bg-purple-600 hover:bg-purple-500 disabled:bg-dark-700 text-white rounded text-xs font-medium transition-colors flex items-center gap-1 disabled:cursor-not-allowed"
                      title="Generate additional edge cases using AI"
                    >
                      {loadingEdgeCases ? (
                        <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      ) : (
                        <Sparkles className="w-3 h-3" />
                      )}
                      AI Edge Cases
                    </button>
                  </div>
                  <ul className="list-disc list-inside space-y-1.5 text-dark-300 bg-dark-900 p-3 rounded-lg border border-dark-800 text-sm font-medium">
                    {description.constraints.map((constraint, index) => (
                      <li key={index}>{constraint}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Original Source Link */}
              {problem.problemLink && (
                <div className="pt-1">
                  <a 
                    href={problem.problemLink} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="px-2 py-1 bg-dark-800 hover:bg-dark-700 rounded text-xs text-white transition-colors flex items-center gap-1.5 border border-dark-700 inline-flex"
                  >
                    <ExternalLink className="w-3 h-3" /> Open Original
                  </a>
                </div>
              )}
            </>
          ) : (
            <div className="bg-dark-900 rounded-lg p-4 border border-dark-800">
              <p className="text-dark-300 italic text-sm">Description unavailable.</p>
            </div>
          )}

          {/* AI Assist Section */}
          {helpData && (
            <div className="space-y-4 pt-3 border-t border-dark-800">
              
              {/* Hints Section */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
                    <Lightbulb className="w-4 h-4 text-yellow-400" /> Hints
                  </h2>
                  <span className="text-xs text-dark-400">
                    {currentHintIndex + 1} / {helpData.hints.length}
                  </span>
                </div>
                
                <div className="space-y-1.5">
                  {helpData.hints.slice(0, currentHintIndex + 1).map((hint, index) => (
                    <div key={index} className="bg-dark-900/50 border border-dark-700 rounded p-2 text-dark-200 text-xs">
                      <span className="font-bold text-brand-orange mr-1">Hint {index + 1}:</span>
                      {hint}
                    </div>
                  ))}
                </div>

                {currentHintIndex < helpData.hints.length - 1 && (
                  <button
                    onClick={() => setCurrentHintIndex(prev => prev + 1)}
                    className="text-xs text-blue-400 hover:text-blue-300 font-medium flex items-center gap-0.5"
                  >
                    Show Next Hint <ChevronRight className="w-3 h-3" />
                  </button>
                )}
              </div>

              {/* Solutions Section */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h2 className="text-sm font-bold text-white flex items-center gap-1.5">
                    <Bot className="w-4 h-4 text-green-400" /> Solution
                  </h2>
                  <button
                    onClick={() => setShowSolution(!showSolution)}
                    className="flex items-center gap-1 text-xs font-medium px-2 py-1 rounded bg-dark-800 hover:bg-dark-700 text-dark-200 transition-colors"
                  >
                    {showSolution ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                    {showSolution ? 'Hide' : 'Show'}
                  </button>
                </div>

                {showSolution && (
                  <div className="bg-dark-900 border border-dark-800 rounded overflow-hidden">
                    {/* Solution Tabs */}
                    <div className="flex border-b border-dark-800">
                      {['brute', 'better', 'optimal'].map((tab) => (
                        helpData.solutions[tab] && (
                          <button
                            key={tab}
                            onClick={() => setActiveSolutionTab(tab)}
                            className={`px-3 py-1.5 text-xs font-medium transition-colors border-b-2 ${
                              activeSolutionTab === tab
                                ? 'border-brand-orange text-white bg-dark-800/50'
                                : 'border-transparent text-dark-400 hover:text-dark-200'
                            }`}
                          >
                            {tab.charAt(0).toUpperCase() + tab.slice(1)}
                          </button>
                        )
                      ))}
                    </div>

                    {/* Solution Content */}
                    <div className="p-3 space-y-3">
                      {helpData.solutions[activeSolutionTab] ? (
                        <>
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Complexity</h4>
                            <p className="text-white font-mono text-xs bg-dark-950 inline-block px-2 py-0.5 rounded border border-dark-800">
                              {helpData.solutions[activeSolutionTab].complexity}
                            </p>
                          </div>
                          
                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Explanation</h4>
                            <p className="text-dark-200 leading-relaxed text-xs">
                              {helpData.solutions[activeSolutionTab].explanation}
                            </p>
                          </div>

                          <div>
                            <h4 className="text-xs font-bold text-dark-400 uppercase tracking-wider mb-1">Code (Java)</h4>
                            <div className="bg-dark-950 rounded p-2 border border-dark-800 overflow-x-auto">
                              <pre className="text-xs font-mono text-blue-300">
                                <code>{helpData.solutions[activeSolutionTab].code}</code>
                              </pre>
                            </div>
                          </div>
                        </>
                      ) : (
                        <p className="text-dark-400 italic text-xs">No specific {activeSolutionTab} approach available.</p>
                      )}
                    </div>
                  </div>
                )}
              </div>

            </div>
          )}
        </div>
      </div>

      {/* Draggable Vertical Divider */}
      <div 
        className="w-1.5 h-full bg-dark-800 cursor-col-resize flex items-center justify-center hover:bg-dark-700 transition-colors shrink-0 group"
        onMouseDown={() => setIsDraggingPanel(true)}
      >
        <GripVertical className="w-3 h-3 text-dark-500 group-hover:text-dark-300" />
      </div>

      {/* Right Column - Code Editor (Full Height) */}
      <div 
        className="h-full"
        style={{ width: `${100 - leftPanelWidth}%` }}
      >
        <CodePanel
          problemId={id}
          onRunCode={handleRunCode}
          edgeCases={edgeCases}
          onGenerateEdgeCases={handleGenerateEdgeCases}
          isGeneratingEdgeCases={loadingEdgeCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={description?.functionSignature}
        />
      </div>
    </div>
  );
}

export default SolveProblemPage;

