import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate, useSearchParams, useLocation } from 'react-router-dom';
import { ArrowLeft, Zap, ExternalLink, Cpu, ChevronRight, Eye, EyeOff, Lightbulb, Terminal, GripVertical, RotateCw } from 'lucide-react';
import SafeMarkdown, { isSafeHttpUrl } from '../components/ui/SafeMarkdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';
import WorkspaceLayout from '../components/workspace/WorkspaceLayout';
import WorkspaceSolutionView from '../components/features/ai/WorkspaceSolutionView';
import ProgressiveHints from '../components/features/ai/ProgressiveHints';
// MotivationalQuote removed here and moved into CodePanel

/**
 * SolveUserProblemPage - A premium practice page for user's saved problems
 * Mirrors the AIInterviewPage experience with full AI hints, solutions, edge cases, and code execution.
 */
function SolveUserProblemPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const isBlindMode = searchParams.get('blind') === 'true';
  
  // Check if problem was passed via state (e.g., from NeetCode sheet)
  const problemFromState = location.state?.problem;
  
  // Problem State (fetched from API or passed via state)
  const [problem, setProblem] = useState(problemFromState || null);
  const [loading, setLoading] = useState(!problemFromState);
  const [error, setError] = useState(null);

  // Description State (may need AI generation if missing)
  const [description, setDescription] = useState(null);
  const [loadingDescription, setLoadingDescription] = useState(false);
  const [descriptionError, setDescriptionError] = useState(null);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('optimal');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50);
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);
  const leftContentRef = useRef(null); // Ref for scrollable container
  const aiAssistRef = useRef(null); // Ref for auto-scrolling

  // Fetch problem on mount (only if not passed via state)
  useEffect(() => {
    // If problem was passed via state, skip API fetch
    if (problemFromState) {
      // Generate description for NeetCode problems if needed
      if (problemFromState.title && !problemFromState.description) {
        fetchDescription(problemFromState.title, 'LeetCode', problemFromState.difficulty, [problemFromState.category], []);
      }
      return;
    }

    const fetchProblem = async () => {
      try {
        setLoading(true);
        const token = await auth.currentUser.getIdToken();
        const response = await api.get(`/problems/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const data = response.data;
        setProblem(data);
        
        // Check if description exists
        if (data.description && typeof data.description === 'object' && data.description.description) {
          setDescription(data.description);
        } else if (data.title) {
          // Need to generate description
          fetchDescription(data.title, data.platform, data.difficulty, data.topics, data.patterns);
        }
      } catch (err) {
        console.error('Failed to fetch problem:', err);
        setError('Failed to load problem');
      } finally {
        setLoading(false);
      }
    };

    if (id) fetchProblem();
  }, [id, problemFromState]);

  // Auto-generate solution and content when description loads
  useEffect(() => {
    if (description && problem && !helpData && !loadingHelp) {
      handleFetchAIContent({ mode: 'full' });
    }
  }, [description, problem]);

  // Panel resizing handlers
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    const containerRect = containerRef.current.getBoundingClientRect();
    let newWidth = ((e.clientX - containerRect.left) / containerRect.width) * 100;
    setLeftPanelWidth(Math.max(25, Math.min(75, newWidth)));
  }, [isDraggingPanel]);

  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    }
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const fetchDescription = async (title, platform, difficulty, topics, patterns) => {
    try {
      setLoadingDescription(true);
      setDescriptionError(null);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-description', { 
        title, 
        platform: platform || 'LeetCode',
        difficulty: difficulty || 'Medium',
        topics: topics || [],
        patterns: patterns || []
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDescription(response.data);
    } catch (error) {
      console.error('Failed to fetch description:', error);
      setDescriptionError(error.response?.data?.error || error.message || 'Failed to load problem description');
    } finally {
      setLoadingDescription(false);
    }
  };

  const handleAIAssist = async (forceRefresh = false) => {
    if (helpData?.solutions?.optimal && !forceRefresh) return;
    
    // Start fetching AI content
    await handleFetchAIContent({ forceRefresh, mode: 'full' });
    
    // User requested a 3-second delay for the "on click effect" (scrolling)
    setTimeout(() => {
      const container = leftContentRef.current;
      const target = aiAssistRef.current;
      
      if (target) {
        target.scrollIntoView({ 
          behavior: 'smooth', 
          block: 'start' 
        });
      } else if (container) {
        // Fallback: strictly scroll to bottom
        container.scrollTo({
          top: container.scrollHeight,
          behavior: 'smooth'
        });
      }
    }, 1000);
  };

  const handleGenerateEdgeCases = async () => {
    await handleFetchAIContent({ 
      forceRefresh: true, 
      mode: 'edge_cases_only',
      providedSolution: helpData?.solutions?.optimal?.code || null
    });
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId || id
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  // Handle Analyze with AI
  const handleAnalyzeCode = async (code, executionFeedback) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const optimalComplexity = helpData?.solutions?.optimal?.complexity || null;
      
      const response = await api.post('/ai/analyze-code', {
        code,
        problemDescription: description?.description || problem?.title || '',
        examples: description?.examples || [],
        constraints: description?.constraints || [],
        optimalComplexity,
        executionFeedback
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      return response.data;
    } catch (error) {
      console.error('Failed to analyze code:', error);
      throw new Error(error.response?.data?.error || 'Failed to analyze code');
    }
  };

  const handleFetchAIContent = async (options = {}) => {
    const config = typeof options === 'boolean' ? { forceRefresh: options } : options;
    const { forceRefresh = false, mode = 'full', providedSolution = null } = config;

    if ((loadingEdgeCases || loadingHelp) && !forceRefresh) return;
    if (!problem || !description) return;

    try {
      if (mode === 'full') {
        setLoadingEdgeCases(true);
        setLoadingHelp(true);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(true);
      }

      const token = await auth.currentUser.getIdToken();
      
      const response = await api.post('/ai/problem-help', {
        title: problem.title,
        description: description.description || description,
        difficulty: problem.difficulty || 'Medium',
        pattern: problem.patterns?.[0] || null,
        examples: description.examples || [],
        constraints: description.constraints || [],
        functionSignature: description.functionSignature || null,
        forceRefresh: forceRefresh,
        mode: mode,
        providedSolution: providedSolution,
        existingEdgeCases: (forceRefresh || mode === 'edge_cases_only') ? null : (edgeCases || null)
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });

      const data = response.data;

      if (data.hints?.length > 0 || data.solutions?.optimal) {
        setHelpData({
          hints: data.hints || [],
          solutions: data.solutions
        });
      }

      let generatedEdgeCases = data.edgeCases || [];
      
      // Normalize: ensure expectedOutput is set (backend might return 'expected')
      if (Array.isArray(generatedEdgeCases)) {
        generatedEdgeCases = generatedEdgeCases.map(tc => ({
          ...tc,
          expectedOutput: tc.expectedOutput ?? tc.expected ?? 'N/A'
        }));
      }

      if (generatedEdgeCases.length > 0) {
        setEdgeCases(generatedEdgeCases);
        const jsonTestFormat = convertEdgeCasesToJsonFormat(generatedEdgeCases);
        setAutoGeneratedInput(jsonTestFormat);
      }

    } catch (error) {
      console.error('Failed to fetch AI content:', error);
      if (forceRefresh) alert('Failed to regenerate content.');
    } finally {
      if (mode === 'full') {
        setLoadingEdgeCases(false);
        setLoadingHelp(false);
      } else if (mode === 'edge_cases_only') {
        setLoadingEdgeCases(false);
      }
    }
  };

  // Automatic scroll removed in favor of the manual 3s delay requested by user
  /*
  useEffect(() => {
    if (helpData && aiAssistRef.current) {
      const timer = setTimeout(() => {
        aiAssistRef.current.scrollIntoView({ 
          behavior: 'smooth', 
          block: 'start'
        });
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [helpData]);
  */

  const parseParamNames = (signature) => {
    if (!signature) return [];
    try {
      const match = signature.match(/\((.*?)\)/);
      if (!match || !match[1]) return [];
      return match[1].split(',').map(param => {
        const parts = param.trim().split(/\s+/);
        return parts[parts.length - 1];
      });
    } catch (e) {
      return [];
    }
  };

  const convertEdgeCasesToJsonFormat = (cases) => {
    const methodName = getMethodName(problem.title, description?.functionSignature);
    const paramNames = parseParamNames(description?.functionSignature);

    const tests = cases.map(edgeCase => {
      if (edgeCase.args && Array.isArray(edgeCase.args)) {
        return { args: edgeCase.args, expected: edgeCase.expected || edgeCase.expectedOutput };
      }

      let args = [];
      const input = edgeCase.input;

      if (paramNames.length > 0 && typeof input === 'object' && input !== null && !Array.isArray(input)) {
        args = paramNames.map(name => {
          if (input[name] !== undefined) return input[name];
          const key = Object.keys(input).find(k => k.toLowerCase() === name.toLowerCase());
          return key ? input[key] : null;
        });
        const validArgs = args.filter(a => a !== null);
        if (validArgs.length === 0 && Object.keys(input).length > 0) {
          args = Object.values(input);
        }
      } else {
        if (paramNames.length === 1 && Array.isArray(input)) {
          args = [input];
        } else {
          args = parseInputToArgs(input);
        }
      }

      return { args: args, expected: edgeCase.expected || edgeCase.expectedOutput };
    });

    return JSON.stringify({ method: methodName, tests: tests }, null, 2);
  };

  const getMethodName = (title, functionSignature) => {
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) return match[1];
    }
    if (!title) return 'solve';
    return title.replace(/[^a-zA-Z0-9\s]/g, '').split(' ')
      .map((word, i) => i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  };

  const parseInputToArgs = (input) => {
    if (Array.isArray(input)) {
      const isPrimitiveList = input.every(i => typeof i === 'number' || typeof i === 'string' || typeof i === 'boolean');
      if (isPrimitiveList) return [input];
      return input;
    }
    if (typeof input === 'object' && input !== null) return Object.values(input);
    return [input];
  };

  const obfuscateSignature = (signature) => {
    if (!signature) return signature;
    // Replace method name with 'solve'
    // Regex matches: return type + space + method name + space* + (
    return signature.replace(/(\s+)([a-zA-Z0-9_]+)(\s*\()/g, '$1solve$3');
  };

  // Prepare display data based on blind mode
  const displayProblemTitle = isBlindMode ? 'Mystery Problem' : problem?.title;
  
  const displayDescription = description ? {
    ...description,
    description: description.description, // Keep original text for now (maybe obscure later?)
    functionSignature: isBlindMode && description.functionSignature 
      ? obfuscateSignature(description.functionSignature) 
      : description.functionSignature
  } : null;

  if (loading) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange mb-4"></div>
        <h2 className="text-xl font-bold text-white mb-2">Loading Problem...</h2>
        <p className="text-dark-400">Setting up your practice environment.</p>
      </div>
    );
  }

  if (error || !problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex flex-col items-center justify-center text-dark-300">
        <p className="mb-4">{error || 'Problem not found.'}</p>
        <button 
          onClick={() => navigate('/')}
          className="px-4 py-2 bg-dark-800 rounded hover:bg-dark-700 transition-colors"
        >
          Go Back
        </button>
      </div>
    );
  }

  return (
    <WorkspaceLayout
      title={displayProblemTitle}
      difficulty={problem.difficulty}
      platform={problem.platform}
      platformUrl={isSafeHttpUrl(problem.platformUrl) ? problem.platformUrl : undefined}
      status={problem.status}
      leftContent={
        <div className="h-full flex flex-col overflow-hidden">
          {/* AI Assist Toolbar Banner */}
          <div className="flex items-center justify-between p-3 rounded-xl bg-surface border border-border m-4 mb-0">
            <div className="flex items-center gap-2">
              <Zap className="w-4 h-4 text-primary" />
              <span className="text-xs font-semibold text-foreground">AI Intuition & Copilot</span>
            </div>
            {(!helpData || !helpData.solutions) ? (
              loadingHelp ? (
                <div className="flex items-center gap-2 text-xs text-foreground-subtle animate-pulse">
                  <div className="w-3 h-3 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                  Generating Hints...
                </div>
              ) : null
            ) : (
              <button
                type="button"
                onClick={() => handleAIAssist(true)}
                disabled={loadingHelp}
                className="text-xs font-medium text-primary hover:underline"
              >
                Regenerate Guidance
              </button>
            )}
          </div>

          {/* Content */}
          <div ref={leftContentRef} className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
          {loadingDescription ? (
            <div className="flex flex-col items-center justify-center py-12 text-dark-400">
              <div className="w-8 h-8 border-2 border-brand-orange/30 border-t-brand-orange rounded-full animate-spin mb-4" />
              <p>Fetching problem description...</p>
            </div>
          ) : descriptionError ? (
            <div className="bg-difficulty-hard/10 border border-difficulty-hard/20 rounded-xl p-6 text-center">
              <p className="text-difficulty-hard mb-4">{descriptionError}</p>
              <button
                onClick={() => fetchDescription(problem?.title, problem?.platform, problem?.difficulty, problem?.topics || [problem?.category], problem?.patterns || [])}
                className="px-4 py-2 bg-brand-orange/20 hover:bg-brand-orange/30 text-brand-orange rounded-lg font-medium transition-colors"
              >
                Retry Loading Description
              </button>
            </div>
          ) : description ? (
            <>
              {/* Description */}
              <div className="bg-dark-900 p-5 rounded-xl border border-dark-800">
                <h2 className="text-[1.15rem] font-[800] text-white mb-4">Description</h2>
                <div className="prose prose-invert max-w-none text-dark-200 text-[1.1rem] font-[450] leading-loose">
                  <SafeMarkdown
                    components={{
                      p: ({node, children}) => <p className="mb-4 last:mb-0 leading-7 text-[15px] tracking-wide text-dark-300">{children}</p>,
                      strong: ({node, children}) => <strong className="text-brand-orange font-bold">{children}</strong>,
                      code: ({node, inline, className, children, ...props}) => {
                        // Check if this is inline code (no className means no language specified = inline)
                        const isInline = !className && (inline !== false);
                        return isInline ? (
                          <code className="bg-dark-800/80 text-brand-orange px-1.5 py-0.5 rounded text-sm font-mono border border-dark-700" {...props}>{children}</code>
                        ) : (
                          <pre className="bg-dark-950 rounded-lg p-3 my-4 border border-dark-800 overflow-x-auto">
                            <code className="text-sm text-dark-200 font-mono" {...props}>{children}</code>
                          </pre>
                        );
                      },
                      ul: ({node, children}) => <ul className="list-disc list-inside space-y-2 my-4 ml-2 text-dark-300">{children}</ul>,
                      ol: ({node, children}) => <ol className="list-decimal list-inside space-y-2 my-4 ml-2 text-dark-300">{children}</ol>,
                      li: ({node, children}) => <li className="text-dark-300 leading-relaxed">{children}</li>,
                      h1: ({node, children}) => <h1 className="text-xl font-bold text-white mt-6 mb-3">{children}</h1>,
                      h2: ({node, children}) => <h2 className="text-lg font-bold text-white mt-5 mb-2">{children}</h2>,
                      h3: ({node, children}) => <h3 className="text-base font-bold text-white mt-4 mb-2">{children}</h3>,
                      blockquote: ({node, children}) => <blockquote className="border-l-4 border-brand-orange/50 pl-4 my-4 text-dark-300 italic">{children}</blockquote>
                    }}
                  >
                    {typeof displayDescription === 'string' ? displayDescription : displayDescription.description}
                  </SafeMarkdown>
                </div>
                
                {displayDescription.functionSignature && (
                  <div className="mt-6 p-4 bg-dark-950 rounded-lg border border-dark-800">
                    <p className="text-[14px] font-[500] text-dark-400 mb-2">Function Signature:</p>
                    <code className="text-base text-green-400 font-mono font-[500]">{displayDescription.functionSignature}</code>
                  </div>
                )}
              </div>

              {/* Examples */}
              {displayDescription.examples && displayDescription.examples.length > 0 && (
                <div className="space-y-4">
                  <h2 className="text-[1.3rem] font-[800] text-white">Examples</h2>
                  <div className="grid gap-4">
                    {displayDescription.examples.map((example, index) => (
                      <div key={index} className="bg-dark-900 rounded-lg p-5 border border-dark-800">
                        <div className="space-y-3 font-mono text-base font-[500]">
                          <div>
                            <span className="text-dark-400">Input:</span> <span className="text-white">{typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}</span>
                          </div>
                          <div>
                            <span className="text-dark-400">Output:</span> <span className="text-white">{typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}</span>
                          </div>
                          {example.explanation && (
                            <div className="pt-3 text-dark-200 font-sans text-[14.5px] font-[450] leading-relaxed">
                              <span className="text-dark-400 font-[800] uppercase tracking-wider block mb-1.5">Explanation:</span>
                              {example.explanation}
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Constraints */}
              {displayDescription.constraints && displayDescription.constraints.length > 0 && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-[1.3rem] font-[800] text-white">Constraints</h2>
                  </div>
                  <ul className="list-disc list-inside space-y-2 text-dark-200 bg-dark-900 p-5 rounded-lg border border-dark-800 text-[1.1rem] font-[450]">
                    {displayDescription.constraints.map((constraint, index) => (
                      <li key={index}>{constraint}</li>
                    ))}
                  </ul>
                </div>
              )}



              {/* AI Assist Section */}
              {helpData && (
                <div ref={aiAssistRef} className="space-y-6 pt-6 border-t border-dark-800">
                  {/* Progressive Socratic Hints */}
                  {helpData.hints && helpData.hints.length > 0 && (
                    <ProgressiveHints hints={helpData.hints} />
                  )}

                  {/* Solutions Section */}
                  {helpData.solutions && (
                    <div className="space-y-3 pt-4 border-t border-border">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Cpu className="w-4 h-4 text-primary" />
                          <h3 className="text-xs font-semibold text-foreground uppercase tracking-wider">
                            Verified Production Solution
                          </h3>
                        </div>
                        <button
                          type="button"
                          onClick={(e) => { e.stopPropagation(); setShowSolution(!showSolution); }}
                          className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-lg bg-surface-raised hover:bg-surface-hover text-foreground-muted hover:text-foreground border border-border transition-colors"
                        >
                          {showSolution ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                          {showSolution ? 'Hide Solution' : 'Reveal Solution'}
                        </button>
                      </div>

                      {showSolution && (
                        <WorkspaceSolutionView
                          solutions={helpData.solutions}
                          initialTier={activeSolutionTab}
                        />
                      )}
                    </div>
                  )}
                </div>
              )}
            </>
          ) : (
            <div className="bg-dark-900 rounded-lg p-6 border border-dark-800">
              <p className="text-dark-300 italic">Description unavailable. Click AI Assist to generate.</p>
            </div>
          )}
        </div>
      </div>

      }
      rightContent={
        <CodePanel
          problemId={id}
          onRunCode={handleRunCode}
          edgeCases={edgeCases}
          onGenerateEdgeCases={handleGenerateEdgeCases}
          isGeneratingEdgeCases={loadingEdgeCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={displayDescription?.functionSignature}
          onAnalyzeCode={handleAnalyzeCode}
          problemDescription={displayDescription?.description}
          examples={displayDescription?.examples}
          constraints={displayDescription?.constraints}
          optimalComplexity={helpData?.solutions?.optimal?.complexity}
        />
      }
    />
  );
}

export default SolveUserProblemPage;
