import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Bot, ChevronRight, Eye, EyeOff, Lightbulb, ExternalLink, Sparkles, GripVertical, Code2, ListChecks, Terminal, PlayCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../utils/api';
import { auth } from '../config/firebase';
import CodePanel from '../components/features/code/CodePanel';

import MotivationalQuote from '../components/ui/MotivationalQuote';

function SolveProblemPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [problem, setProblem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Description State
  const [description, setDescription] = useState(null);
  const [loadingDescription, setLoadingDescription] = useState(false);

  // AI Assist State
  const [helpData, setHelpData] = useState(null);
  const [loadingHelp, setLoadingHelp] = useState(false);
  const [currentHintIndex, setCurrentHintIndex] = useState(0);
  const [showSolution, setShowSolution] = useState(false);
  const [activeSolutionTab, setActiveSolutionTab] = useState('optimal');

  // Code Execution State
  const [edgeCases, setEdgeCases] = useState(null);
  const [loadingEdgeCases, setLoadingEdgeCases] = useState(false);
  const [autoGeneratedInput, setAutoGeneratedInput] = useState('');
  
  // Ref to track if edge cases have been auto-generated (prevents duplicate API calls)
  const edgeCasesGeneratedRef = useRef(false);

  // Resizable panels state
  const [leftPanelWidth, setLeftPanelWidth] = useState(50); // percentage
  const [isDraggingPanel, setIsDraggingPanel] = useState(false);
  const containerRef = useRef(null);

  useEffect(() => {
    const fetchProblem = async () => {
      try {
        setLoading(true);
        const response = await api.get(`/revisions/${id}`);
        const data = response.data || response;
        setProblem(data);
        
        // If description is missing, fetch it using AI
        if (!data.description && data.problemTitle) {
          fetchDescription(data.problemTitle);
        } else if (data.description) {
          setDescription(data.description);
        } else {
          setDescription('Problem details unavailable.');
        }
      } catch (err) {
        console.error('Failed to fetch problem:', err);
        setError('Failed to load problem');
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchProblem();
    }
  }, [id]);

  // Auto-generate AI edge cases when description loads
  // Uses ref to prevent duplicate generation when other state changes cause re-renders
  useEffect(() => {
    if (description && problem && !edgeCasesGeneratedRef.current && !loadingEdgeCases) {
      // Mark as generated to prevent duplicate calls
      edgeCasesGeneratedRef.current = true;
      handleGenerateEdgeCases();
    }
  }, [description, problem, loadingEdgeCases]);

  // Handle mouse move for panel resizing
  const handlePanelMouseMove = useCallback((e) => {
    if (!isDraggingPanel || !containerRef.current) return;
    
    const container = containerRef.current;
    const containerRect = container.getBoundingClientRect();
    const mouseX = e.clientX - containerRect.left;
    
    // Calculate percentage (clamp between 25% and 75%)
    let newWidth = (mouseX / containerRect.width) * 100;
    newWidth = Math.max(25, Math.min(75, newWidth));
    
    setLeftPanelWidth(newWidth);
  }, [isDraggingPanel]);

  // Handle mouse up to stop panel dragging
  const handlePanelMouseUp = useCallback(() => {
    setIsDraggingPanel(false);
    document.body.style.cursor = 'default';
    document.body.style.userSelect = 'auto';
  }, []);

  // Add/remove global event listeners for panel dragging
  useEffect(() => {
    if (isDraggingPanel) {
      document.addEventListener('mousemove', handlePanelMouseMove);
      document.addEventListener('mouseup', handlePanelMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    }
    
    return () => {
      document.removeEventListener('mousemove', handlePanelMouseMove);
      document.removeEventListener('mouseup', handlePanelMouseUp);
    };
  }, [isDraggingPanel, handlePanelMouseMove, handlePanelMouseUp]);

  const fetchDescription = async (title) => {
    try {
      setLoadingDescription(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-description', {
        title: title
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDescription(response.data);
    } catch (error) {
      console.error('Failed to fetch description:', error);
    } finally {
      setLoadingDescription(false);
    }
  };

  const handleAIAssist = async () => {
    if (helpData) return;

    try {
      setLoadingHelp(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/problem-help', {
        title: problem.problemTitle,
        description: description?.description || `Problem titled "${problem.problemTitle}"`,
        difficulty: problem.difficulty || 'Medium',
        examples: description?.examples || [],
        constraints: description?.constraints || [],
        functionSignature: description?.functionSignature || null,
        existingEdgeCases: edgeCases // Pass existing edge cases to avoid redundant generation
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setHelpData(response.data);
      
      // Update edge cases with the ones from help response (these have computed expected outputs!)
      if (response.data.edgeCases && response.data.edgeCases.length > 0) {
        setEdgeCases(response.data.edgeCases);
        const jsonTestFormat = convertEdgeCasesToJsonFormat(response.data.edgeCases, problem);
        setAutoGeneratedInput(jsonTestFormat);
        console.log('Updated edge cases with computed expected outputs from AI Assist');
      }
    } catch (error) {
      console.error('Failed to get AI help:', error);
      alert('Failed to generate AI hints and solutions.');
    } finally {
      setLoadingHelp(false);
    }
  };

  const handleRunCode = async (code, stdin, problemId) => {
    try {
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/run/java', {
        source: code,
        stdin: stdin,
        problemId: problemId
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      return response.data;
    } catch (error) {
      console.error('Failed to run code:', error);
      throw new Error(error.response?.data?.error || 'Failed to execute code');
    }
  };

  const handleGenerateEdgeCases = async () => {
    if (loadingEdgeCases || !description) return;

    try {
      setLoadingEdgeCases(true);
      const token = await auth.currentUser.getIdToken();
      const response = await api.post('/ai/edge-cases', {
        title: problem.problemTitle,
        description: description.description || description,
        examples: description.examples || [],
        constraints: description.constraints || [],
        functionSignature: description.functionSignature || null,
        providedSolution: helpData?.solutions?.optimal?.code // Pass solution if we have it to compute outputs
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const generatedEdgeCases = response.data;
      setEdgeCases(generatedEdgeCases);
      
      if (generatedEdgeCases && generatedEdgeCases.length > 0) {
        const jsonTestFormat = convertEdgeCasesToJsonFormat(generatedEdgeCases, problem);
        setAutoGeneratedInput(jsonTestFormat);
      }
    } catch (error) {
      console.error('Failed to generate edge cases:', error);
    } finally {
      setLoadingEdgeCases(false);
    }
  };

  const convertEdgeCasesToJsonFormat = (edgeCases, problem) => {
    // At this point, description should be loaded (we only generate edge cases after description loads)
    // Use description.functionSignature directly if available
    const methodName = getMethodName(problem.problemTitle, description?.functionSignature);
    
    console.log('Converting edge cases to JSON format...');
    console.log('Method name extracted:', methodName);
    console.log('Function signature:', description?.functionSignature);
    
    const tests = edgeCases.map(edgeCase => {
      const args = parseInputToArgs(edgeCase.input);
      const expected = edgeCase.expectedOutput;
      
      return {
        args: args,
        expected: expected
      };
    });

    const jsonResult = JSON.stringify({
      method: methodName,
      tests: tests
    }, null, 2);
    
    console.log('Generated JSON input (first 500 chars):', jsonResult.substring(0, 500));
    return jsonResult;
  };

  const getMethodName = (title, functionSignature) => {
    if (functionSignature) {
      const match = functionSignature.match(/\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match && match[1]) {
        return match[1];
      }
    }
    return inferMethodNameFromTitle(title);
  };

  const inferMethodNameFromTitle = (title) => {
    if (!title) return 'solve';
    
    const commonMethods = {
      'two sum': 'twoSum',
      'three sum': 'threeSum',
      'add two numbers': 'addTwoNumbers',
      'longest substring': 'lengthOfLongestSubstring',
      'median of two sorted arrays': 'findMedianSortedArrays',
      'reverse integer': 'reverse',
      'palindrome number': 'isPalindrome',
      'valid parentheses': 'isValid',
      'merge two sorted lists': 'mergeTwoLists'
    };

    const lowerTitle = title.toLowerCase();
    for (const [key, method] of Object.entries(commonMethods)) {
      if (lowerTitle.includes(key)) {
        return method;
      }
    }

    return title
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(' ')
      .map((word, index) => {
        if (index === 0) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  };

  const parseInputToArgs = (input) => {
    // If already an array, check if it's an array of arguments or a single array argument
    if (Array.isArray(input)) {
      // Check if this looks like a single array argument (e.g., [1,2,3] for int[] param)
      // vs multiple arguments (e.g., [[1,2], 5] for int[] and int params)
      // If all elements are primitives, treat as single array argument
      const allPrimitives = input.every(item => 
        typeof item === 'number' || typeof item === 'string' || typeof item === 'boolean'
      );
      if (allPrimitives && input.length > 0) {
        return [input]; // Wrap as single array argument
      }
      return input;
    }
    if (typeof input === 'object' && input !== null) {
      // If it has keys that look like parameter names (e.g., from AI), extract values
      // This is a heuristic: if it's a plain object with specific keys, use the values.
      // But if it's like a ListNode or other custom type (though AI doesn't return that directly usually), 
      // we might need more logic. For now, Object.values is best for multi-param methods.
      const values = Object.values(input);
      if (values.length > 0) return values;
      return [input];
    }
    
    if (typeof input === 'string') {
      const trimmed = input.trim();
      if (trimmed.includes('=')) {
        const parts = trimmed.split(/,\s*(?![^\[\]]*\])/);
        const args = [];
        for (const part of parts) {
          if (part.includes('=')) {
            const value = part.split('=')[1].trim();
            try { args.push(JSON.parse(value)); } catch (e) { args.push(value); }
          } else {
            try { args.push(JSON.parse(part.trim())); } catch (e) { args.push(part.trim()); }
          }
        }
        return args;
      }
      try {
        const parsed = JSON.parse(trimmed);
        // If parsed is an array, wrap it as a single argument
        // (the array itself is the argument, not its elements)
        if (Array.isArray(parsed)) {
          return [parsed]; // Wrap array as single argument
        }
        return [parsed];
      } catch (e) {
        try { return JSON.parse(`[${trimmed}]`); } catch (e2) { return [input]; }
      }
    }
    return [input];
  };


  if (loading) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-orange"></div>
          <p className="text-dark-400 font-medium animate-pulse">Loading problem workspace...</p>
        </div>
      </div>
    );
  }

  if (error || !problem) {
    return (
      <div className="min-h-screen bg-dark-950 flex items-center justify-center">
        <div className="text-center p-8 bg-dark-900 rounded-2xl border border-dark-800 shadow-xl max-w-md">
           <div className="w-16 h-16 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4 border border-red-500/20">
             <Bot className="w-8 h-8 text-red-500" />
           </div>
           <h2 className="text-xl font-bold text-dark-100 mb-2">{error || 'Problem not found'}</h2>
           <button 
            onClick={() => navigate('/revision')}
            className="mt-4 px-6 py-2 bg-dark-800 hover:bg-dark-700 text-dark-100 rounded-xl transition-colors font-medium border border-dark-700"
           >
            Back to Dashboard
           </button>
        </div>
      </div>
    );
  }

  return (
    <div ref={containerRef} className="h-screen bg-dark-950 text-dark-100 flex overflow-hidden font-sans">
      {/* Left Column - Problem Description */}
      <div 
        className="h-full flex flex-col border-r border-dark-800 bg-dark-950 relative"
        style={{ width: `${leftPanelWidth}%` }}
      >
        {/* Left Header - Glassmorphic */}
        {/* Left Header - Glassmorphic */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-dark-800 bg-dark-950/80 backdrop-blur-md sticky top-0 z-20">
          <div className="flex items-center gap-4 min-w-0">
            <button 
              onClick={() => navigate('/revision')}
              className="p-2 hover:bg-dark-800/50 rounded-xl transition-all text-dark-400 hover:text-dark-100 group border border-transparent hover:border-dark-700"
              title="Back to Review"
            >
              <ArrowLeft className="w-5 h-5 group-hover:-translate-x-0.5 transition-transform" />
            </button>
            <div className="min-w-0">
              <h1 className="text-lg font-bold text-dark-100 truncate leading-tight">{problem.problemTitle}</h1>
              <div className="flex items-center gap-2 mt-1">
                 <span className={`px-2.5 py-0.5 rounded-md text-[10px] font-black uppercase tracking-wider border ${
                  (problem.difficulty || 'Medium') === 'Easy' ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                  (problem.difficulty || 'Medium') === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20' :
                  'bg-red-500/10 text-red-400 border-red-500/20'
                }`}>
                  {problem.difficulty || 'Medium'}
                </span>
                {problem.topic && (
                   <span className="text-xs text-dark-400 flex items-center gap-1">
                     <span className="w-1 h-1 rounded-full bg-dark-600"></span>
                     {problem.topic}
                   </span>
                )}
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            {!helpData && (
              <button 
                onClick={handleAIAssist}
                disabled={loadingHelp || loadingDescription}
                className="px-4 py-2 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-dark-100 rounded-xl text-sm font-semibold shadow-lg shadow-blue-500/20 transition-all hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 flex items-center gap-2 border border-blue-400/20"
              >
                {loadingHelp ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
                <span className="hidden sm:inline">AI Assist</span>
              </button>
            )}
          </div>
        </div>

        {/* Left Content Scrollable */}
        <div className="flex-1 overflow-y-auto px-6 py-6 space-y-8 no-scrollbar scroll-smooth">
          {loadingDescription ? (
            <div className="flex flex-col items-center justify-center py-20 text-dark-400 space-y-4">
              <div className="w-12 h-12 border-2 border-brand-orange/30 border-t-brand-orange rounded-full animate-spin" />
              <p className="animate-pulse font-medium">Analyzing problem...</p>
            </div>
          ) : description ? (
            <div className="space-y-8 animate-in fade-in duration-500 slide-in-from-bottom-4">
              {/* Description Text */}
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-brand-orange/80 mb-2">
                   <Code2 className="w-5 h-5" />
                   <h2 className="text-sm font-bold uppercase tracking-widest">Problem Statement</h2>
                </div>
                <div className="prose prose-invert prose-p:text-dark-300 prose-headings:text-dark-100 max-w-none text-base leading-relaxed">
                  <ReactMarkdown 
                    components={{
                      code: ({node, inline, className, children, ...props}) => {
                        return inline ? (
                          <code className="bg-dark-800/80 text-brand-orange px-1.5 py-0.5 rounded text-sm font-mono border border-dark-700" {...props}>
                            {children}
                          </code>
                        ) : (
                          <div className="bg-dark-900 rounded-lg p-3 my-4 border border-dark-800 overflow-x-auto">
                            <code className="text-sm text-dark-200 font-mono" {...props}>{children}</code>
                          </div>
                        )
                      }
                    }}
                  >
                    {typeof description === 'string' ? description : description.description}
                  </ReactMarkdown>
                </div>
                
                {/* Function Signature */}
                {description.functionSignature && (
                  <div className="mt-4 group relative overflow-hidden bg-dark-900/40 rounded-xl border border-dark-800 p-4 hover:border-dark-700 transition-colors">
                    <div className="absolute top-0 left-0 w-1 h-full bg-brand-orange/50"></div>
                     <p className="text-xs font-bold text-dark-500 uppercase tracking-wider mb-2 flex items-center gap-2">
                       <Terminal className="w-4 h-4" />
                       Function Signature
                     </p>
                    <code className="text-sm text-green-400 font-mono block break-all">{description.functionSignature}</code>
                  </div>
                )}
              </div>

              {/* Examples */}
              {description.examples && description.examples.length > 0 && (
                <div className="space-y-4">
                  <div className="flex items-center gap-2 text-brand-orange/80">
                     <ListChecks className="w-5 h-5" />
                     <h2 className="text-sm font-bold uppercase tracking-widest">Examples</h2>
                  </div>
                  <div className="grid gap-4">
                    {description.examples.map((example, index) => (
                      <div key={index} className="bg-dark-900/40 rounded-xl p-5 border border-dark-800 hover:border-dark-700 transition-colors shadow-sm">
                        <div className="space-y-3 font-mono text-sm">
                          <div className="flex gap-3">
                            <span className="text-dark-500 font-bold shrink-0 w-12 text-xs uppercase pt-1">Input</span>
                            <span className="text-dark-100 bg-dark-950 px-2 py-1 rounded border border-dark-800/50 block w-full">
                              {typeof example.input === 'object' ? JSON.stringify(example.input) : example.input}
                            </span>
                          </div>
                          <div className="flex gap-3">
                            <span className="text-dark-500 font-bold shrink-0 w-12 text-xs uppercase pt-1">Output</span>
                            <span className="text-dark-100 bg-dark-950 px-2 py-1 rounded border border-dark-800/50 block w-full">
                              {typeof example.output === 'object' ? JSON.stringify(example.output) : example.output}
                            </span>
                          </div>
                          {example.explanation && (
                            <div className="pt-2 pl-[60px] text-dark-300 font-sans text-sm leading-relaxed border-t border-dark-800/50 mt-3">
                              <span className="text-dark-500 font-bold text-xs uppercase tracking-wider inline-block mb-1 mr-2">Explanation:</span>
                              <ReactMarkdown components={{
                                p: ({node, ...props}) => <span {...props} />,
                                code: ({node, ...props}) => <code className="bg-dark-800 px-1 py-0.5 rounded text-brand-orange text-xs" {...props} />
                              }}>
                                {example.explanation}
                              </ReactMarkdown>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Constraints */}
              {description.constraints && description.constraints.length > 0 && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-sm font-bold text-brand-orange/80 uppercase tracking-widest">Constraints</h2>
                    <button
                      type="button"
                      onClick={(e) => { e.stopPropagation(); handleGenerateEdgeCases(); }}
                      disabled={loadingEdgeCases}
                      className="px-3 py-1.5 bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 border border-purple-500/20 hover:border-purple-500/40 rounded-lg text-xs font-bold transition-all flex items-center gap-2 group"
                      title="Generate additional edge cases using AI"
                    >
                      {loadingEdgeCases ? (
                        <div className="w-3 h-3 border-2 border-current border-t-transparent rounded-full animate-spin" />
                      ) : (
                        <Sparkles className="w-3 h-3 group-hover:text-purple-300" />
                      )}
                      Generate Edge Cases
                    </button>
                  </div>
                  <div className="bg-dark-900/40 p-4 rounded-xl border border-dark-800">
                    <ul className="space-y-2.5">
                      {description.constraints.map((constraint, index) => (
                        <li key={index} className="flex items-start gap-3 text-dark-300 text-sm">
                           <span className="w-1.5 h-1.5 rounded-full bg-dark-600 mt-2 shrink-0"></span>
                           <span className="font-mono">{constraint}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* External Link */}
              {problem.problemLink && (
                 <div className="pt-2 flex justify-end">
                  <a 
                    href={problem.problemLink} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="group flex items-center gap-2 text-xs font-medium text-dark-500 hover:text-brand-orange transition-colors"
                  >
                    View on Original Platform <ExternalLink className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
                  </a>
                </div>
              )}
            </div>
          ) : (
            <div className="bg-dark-900/50 rounded-xl p-8 border border-dark-800 border-dashed text-center">
              <p className="text-dark-400 font-medium">Description unavailable. Use AI Assist to generate one.</p>
            </div>
          )}

          {/* AI Assist Section */}
          {helpData && (
            <div className="mt-8 pt-8 border-t border-dark-800/50 animate-in fade-in slide-in-from-bottom-8 duration-700">
              {/* Hints */}
              <div className="space-y-4 mb-8">
                <div className="flex items-center justify-between">
                   <h2 className="text-sm font-bold text-dark-100 flex items-center gap-2">
                    <Lightbulb className="w-4 h-4 text-yellow-400" /> 
                    <span className="bg-gradient-to-r from-yellow-200 to-yellow-500 bg-clip-text text-transparent">Smart Hints</span>
                  </h2>
                  <span className="text-xs font-mono text-dark-500 bg-dark-900 px-2 py-1 rounded border border-dark-800">
                    {currentHintIndex + 1} / {helpData.hints.length}
                  </span>
                </div>
                
                <div className="relative">
                   <div className="bg-gradient-to-br from-dark-900 to-dark-950 border border-dark-800 rounded-xl p-5 shadow-lg relative overflow-hidden group">
                      <div className="absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity">
                         <Lightbulb className="w-24 h-24 text-yellow-500 transform rotate-12" />
                      </div>
                      <div className="relative z-10">
                        <span className="text-yellow-500 text-xs font-bold uppercase tracking-widest mb-2 block">Hint {currentHintIndex + 1}</span>
                        <p className="text-dark-200 text-sm leading-relaxed">{helpData.hints[currentHintIndex]}</p>
                      </div>
                   </div>

                   {currentHintIndex < helpData.hints.length - 1 && (
                    <button
                      onClick={() => setCurrentHintIndex(prev => prev + 1)}
                      className="absolute -bottom-3 right-4 px-3 py-1 bg-dark-800 hover:bg-dark-700 text-blue-400 text-xs font-bold rounded-full border border-dark-700 shadow-lg flex items-center gap-1 transition-all hover:scale-105"
                    >
                      Next Hint <ChevronRight className="w-3 h-3" />
                    </button>
                  )}
                </div>
              </div>

              {/* Solutions */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                   <h2 className="text-sm font-bold text-dark-100 flex items-center gap-2">
                    <Bot className="w-4 h-4 text-green-400" /> 
                    <span className="bg-gradient-to-r from-green-300 to-green-500 bg-clip-text text-transparent">AI Solution</span>
                  </h2>
                  <button
                    type="button"
                    onClick={(e) => { e.stopPropagation(); setShowSolution(!showSolution); }}
                    className={`flex items-center gap-2 text-xs font-bold px-3 py-1.5 rounded-lg transition-all ${
                       showSolution 
                       ? 'bg-dark-800 text-dark-100' 
                       : 'bg-dark-900 text-dark-400 hover:text-dark-100 hover:bg-dark-800'
                    }`}
                  >
                    {showSolution ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
                    {showSolution ? 'Hide Solution' : 'Reveal Solution'}
                  </button>
                </div>

                {showSolution && (
                  <div className="bg-dark-900/80 border border-dark-800 rounded-xl overflow-hidden shadow-2xl animate-in zoom-in-95 duration-300">
                    <div className="flex border-b border-dark-800 bg-dark-950/50">
                      {['optimal', 'better', 'brute'].map((tab) => (
                        helpData.solutions[tab] && (
                          <button
                            key={tab}
                            onClick={() => setActiveSolutionTab(tab)}
                            className={`flex-1 px-4 py-3 text-xs font-bold uppercase tracking-wider transition-all relative ${
                              activeSolutionTab === tab
                                ? 'text-brand-orange bg-dark-900'
                                : 'text-dark-500 hover:text-dark-300 hover:bg-dark-900/50'
                            }`}
                          >
                            {tab}
                            {activeSolutionTab === tab && (
                               <span className="absolute bottom-0 left-0 w-full h-0.5 bg-brand-orange shadow-[0_0_10px_rgba(255,161,22,0.5)]"></span>
                            )}
                          </button>
                        )
                      ))}
                    </div>

                    <div className="p-5 space-y-5 bg-dark-900/50">
                      {helpData.solutions[activeSolutionTab] ? (
                        <>
                          <div className="flex gap-4">
                            <div className="flex-1 space-y-1">
                               <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest">Time & Space</h4>
                               <p className="text-green-400 font-mono text-xs bg-green-500/10 inline-block px-2 py-1 rounded border border-green-500/20">
                                {helpData.solutions[activeSolutionTab].complexity}
                              </p>
                            </div>
                          </div>
                          
                          <div className="space-y-4">
                             <div>
                                <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest mb-2">Intuition & Pattern</h4>
                                <p className="text-dark-200 text-xs leading-relaxed border-l-2 border-brand-orange pl-3 py-1 bg-brand-orange/5 rounded-r">
                                  {helpData.solutions[activeSolutionTab].intuition || helpData.solutions[activeSolutionTab].explanation || helpData.solutions[activeSolutionTab].approach}
                                </p>
                             </div>

                             {helpData.solutions[activeSolutionTab].approachSteps?.length > 0 && (
                               <div>
                                 <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest mb-3">Wait... How it works? (Step-by-Step)</h4>
                                 <div className="space-y-3">
                                   {helpData.solutions[activeSolutionTab].approachSteps.map((step, idx) => (
                                     <div key={idx} className="flex gap-4 text-[13.5px] font-medium group">
                                       <span className="flex-shrink-0 w-6 h-6 rounded-full bg-dark-800 border border-dark-700 flex items-center justify-center text-[10px] font-bold text-brand-orange group-hover:border-brand-orange/50 transition-colors shadow-sm">
                                         {idx + 1}
                                       </span>
                                       <p className="text-dark-100 pt-0.5 leading-relaxed">
                                         {step.replace(/^\w+\s+\d+:\s*/, '')}
                                       </p>
                                     </div>
                                   ))}
                                 </div>
                               </div>
                             )}
                          </div>

                          <div className="space-y-2">
                             <div className="flex justify-between items-center">
                                <h4 className="text-[10px] font-black text-dark-500 uppercase tracking-widest">Implementation</h4>
                                <span className="text-[10px] font-mono text-dark-600">Java</span>
                             </div>
                            <div className="bg-dark-950 rounded-xl p-4 border border-dark-800 overflow-x-auto shadow-inner relative group">
                              <pre className="text-xs font-mono text-blue-300 leading-relaxed">
                                <code>{helpData.solutions[activeSolutionTab].code}</code>
                              </pre>
                            </div>
                          </div>
                        </>
                      ) : (
                        <div className="text-center py-8">
                            <p className="text-dark-400 italic text-sm">No specific {activeSolutionTab} approach available.</p>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Draggable Vertical Divider */}
      <div 
        className="w-4 -ml-2 h-full z-30 cursor-col-resize flex items-center justify-center group outline-none"
        onMouseDown={() => setIsDraggingPanel(true)}
      >
        <div className="w-1 h-full bg-dark-800 group-hover:bg-brand-orange/50 transition-colors shadow-xl"></div>
        <div className="absolute top-1/2 -translate-y-1/2 bg-dark-800 group-hover:bg-brand-orange text-dark-400 group-hover:text-white w-6 h-12 rounded-full flex items-center justify-center transition-all shadow-lg border border-dark-700">
           <GripVertical className="w-3 h-3" />
        </div>
      </div>

      {/* Right Column - Code Editor (Full Height) */}
      <div 
        className="h-full bg-dark-950"
        style={{ width: `${100 - leftPanelWidth}%` }}
      >
        <CodePanel
          problemId={id}
          onRunCode={handleRunCode}
          edgeCases={edgeCases}
          onGenerateEdgeCases={handleGenerateEdgeCases}
          isGeneratingEdgeCases={loadingEdgeCases}
          autoGeneratedInput={autoGeneratedInput}
          functionSignature={description?.functionSignature}
        />
      </div>
      {/* Centered Bottom Quote */}
      <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[60] pointer-events-none">
        <div className="pointer-events-auto">
          <MotivationalQuote 
            category="Resilience" 
            variant="ghost" 
            className="shadow-2xl !bg-black/40 backdrop-blur-md border border-white/5 hover:border-brand-orange/30 transition-colors"
          />
        </div>
      </div>
    </div>
  );
}

export default SolveProblemPage;
