export const DSA_PATTERNS = [
  "Two Pointers",
  "Sliding Window",
  "Fast & Slow Pointers",
  "Merge Intervals",
  "Cyclic Sort",
  "In-place Reversal of a LinkedList",
  "Tree Breadth First Search",
  "Tree Depth First Search",
  "Two Heaps",
  "Subsets",
  "Modified Binary Search",
  "Bitwise XOR",
  "Top K Elements",
  "K-way Merge",
  "0/1 Knapsack (Dynamic Programming)",
  "Unbounded Knapsack (Dynamic Programming)",
  "Fibonacci Numbers (Dynamic Programming)",
  "Palindromic Subsequence (Dynamic Programming)",
  "Longest Common Substring (Dynamic Programming)",
  "Topological Sort (Graph)",
  "Union Find",
  "Trie",
  "Monotonic Stack",
  "Prefix Sum",
  "Kadane's Algorithm",
  "Backtracking",
  "Divide and Conquer",
  "Greedy"
];

export const DSA_TOPICS = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Depth-First Search",
  "Binary Search",
  "Database",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers",
  "Bit Manipulation",
  "Stack",
  "Design",
  "Heap (Priority Queue)",
  "Backtracking",
  "Graph",
  "Simulation",
  "Prefix Sum",
  "Sliding Window",
  "Counting",
  "LinkedList",
  "Union Find",
  "Recursion",
  "Binary Search Tree",
  "Trie",
  "Monotonic Stack",
  "Ordered Set",
  "Queue",
  "Geometry",
  "Game Theory",
  "Segment Tree"
];
